import type { RecipeSeed } from './recipes';

/**
 * Italy, Spain and Greece: the "Italien & Spanien" rotation week, its sauces, the Greek
 * Tirokafteri and the Greek Gönn-Essen, plus two weekend dishes.
 */
export const SOUTHERN_RECIPES: RecipeSeed[] = [
  // =================================================================== Saucen
  {
    slug: 'pesto-skyr',
    name: 'Basilikum-Pesto-Skyr',
    mealType: 'sauce',
    description: 'Basis Knoblauch & Kräuter: cremiges Pesto aus frischem Basilikum, Parmesan und gerösteten Mandeln – mit Skyr statt Öl-Bergen.',
    flavorHack: 'Die Mandeln trocken anrösten und das Basilikum erst ganz am Schluss kurz mitmixen – so bleibt das Pesto grün und schmeckt nach Sommer statt nach Heu.',
    servings: 6,
    prepMinutes: 6,
    cookMinutes: 2,
    fridgeDays: 4,
    freezerDays: 60,
    eatCold: true,
    tags: ['basis-knoblauch', 'italienisch', 'kalt'],
    equipment: [],
    steps: [
      'Mandeln in der trockenen Pfanne anrösten, fein hacken.',
      'Basilikum, Knoblauch, Parmesan, Olivenöl und Zitronensaft fein hacken oder mit dem Pürierstab mixen.',
      'Mit Skyr und den Mandeln verrühren, salzen.',
    ],
    per: [
      ['skyr', 30],
      ['basilikum', 5],
      ['parmesan', 3],
      ['olivenoel', 3],
      ['mandeln', 2],
      ['knoblauch', 1],
      ['zitrone', 3],
    ],
  },
  {
    slug: 'skyr-aioli',
    name: 'Skyr-Aioli',
    mealType: 'sauce',
    description: 'Basis Knoblauch & Kräuter: spanische Knoblauchcreme – kräftig nach Knoblauch, leicht zitronig, zu Paella, Albóndigas und Kartoffeln.',
    flavorHack: 'Den Knoblauch mit einer Prise Salz zu Paste zerreiben und 5 Minuten im Zitronensaft ziehen lassen – dann wird die Aioli rund statt scharf.',
    servings: 6,
    prepMinutes: 4,
    cookMinutes: 0,
    fridgeDays: 4,
    freezerDays: 0,
    eatCold: true,
    tags: ['basis-knoblauch', 'spanisch', 'kalt'],
    equipment: [],
    steps: ['Knoblauch mit Salz zu Paste zerreiben, mit Zitronensaft verrühren.', 'Skyr, Senf und Olivenöl einrühren.', 'Mit Pfeffer abschmecken.'],
    per: [
      ['skyr', 35],
      ['knoblauch', 2],
      ['olivenoel', 4],
      ['zitrone', 3],
      ['senf', 1],
    ],
  },
  {
    slug: 'romesco-light',
    name: 'Romesco light',
    mealType: 'sauce',
    description: 'Basis Knoblauch & Kräuter: rauchige katalanische Paprika-Mandel-Sauce – großartig zu Fleischbällchen, Huhn und Ofenkartoffeln.',
    flavorHack: 'Die Paprika im Ofen rösten, bis die Haut schwarze Blasen wirft – das Röstaroma plus geräuchertes Paprikapulver ist der ganze Trick.',
    servings: 6,
    prepMinutes: 5,
    cookMinutes: 20,
    fridgeDays: 5,
    freezerDays: 60,
    eatCold: true,
    tags: ['basis-knoblauch', 'spanisch'],
    equipment: ['Backofen'],
    steps: [
      'Paprika bei 220 °C 20 Minuten rösten, bis die Haut Blasen wirft.',
      'Mit Mandeln, Tomatenmark, Knoblauch, Paprikapulver, Essig und Olivenöl pürieren.',
      'Salzen – soll dickflüssig sein.',
    ],
    per: [
      ['paprika', 40],
      ['mandeln', 4],
      ['tomatenmark', 5],
      ['knoblauch', 1],
      ['paprikapulver', 1],
      ['essig', 3],
      ['olivenoel', 3],
    ],
  },
  {
    slug: 'tirokafteri-light',
    name: 'Tirokafteri light',
    mealType: 'sauce',
    description: 'Basis Skyr-Joghurt: der scharfe griechische Feta-Dip – cremig, salzig, mit Röstpaprika und Chili.',
    flavorHack: 'Den Hirtenkäse mit der Gabel nur grob zerdrücken statt glatt mixen – kleine Stückchen machen den Dip spannender.',
    servings: 6,
    prepMinutes: 5,
    cookMinutes: 0,
    fridgeDays: 4,
    freezerDays: 0,
    eatCold: true,
    tags: ['basis-skyr', 'griechisch', 'scharf', 'kalt'],
    equipment: [],
    steps: ['Hirtenkäse zerdrücken.', 'Mit Skyr, fein gehackter Paprika, Chili, Zitronensaft und Olivenöl verrühren.'],
    per: [
      ['hirtenkaese', 10],
      ['skyr', 30],
      ['paprika', 10],
      ['chiliflocken', 0.3],
      ['zitrone', 2],
      ['olivenoel', 1],
    ],
  },

  // =================================================================== Italien & Spanien – Meal Prep
  {
    slug: 'pesto-haehnchen-nudelsalat',
    name: 'Pesto-Hähnchen-Nudelsalat mit Rucola & Mozzarella',
    mealType: 'main',
    description: 'Italienischer Nudelsalat mit Zitronen-Hähnchen, Cherrytomaten, Mozzarella und Rucola – zieht über Nacht durch und schmeckt kalt am besten.',
    flavorHack: 'Die Tomaten halbieren, salzen und 10 Minuten stehen lassen – ihr Saft verbindet sich mit dem Pesto zu einem Dressing, der Salat wird nie trocken.',
    servings: 3,
    prepMinutes: 15,
    cookMinutes: 15,
    fridgeDays: 4,
    freezerDays: 0,
    eatCold: true,
    tags: ['italienisch', 'kalt', 'high-protein'],
    equipment: ['Herd'],
    steps: [
      'Nudeln bissfest kochen, kalt abspülen.',
      'Hühnerbrust mit Zitrone, Salz und Pfeffer würzen und 6 Minuten pro Seite braten, in Streifen schneiden.',
      'Tomaten halbieren und salzen, Mozzarella zupfen.',
      'Alles mischen, Pesto-Skyr extra mitnehmen, Rucola erst vor dem Essen drauf.',
    ],
    per: [
      ['vollkornnudeln', 65],
      ['huehnerbrust', 105],
      ['tomaten', 100],
      ['mozzarella-light', 30],
      ['rucola', 25],
      ['zitrone', 5],
      ['olivenoel', 4],
    ],
  },
  {
    slug: 'albondigas-patatas',
    name: 'Albóndigas in Tomatensauce mit Ofen-Patatas',
    mealType: 'main',
    description: 'Spanische Fleischbällchen aus Pute und Rind in rauchiger Paprika-Tomatensauce, dazu knusprige Ofenkartoffeln – wie in der Tapas-Bar.',
    flavorHack: 'Die Bällchen zuerst scharf anbraten und erst dann in der Sauce fertig ziehen lassen – außen Kruste, innen saftig. Geräuchertes Paprikapulver ist Pflicht.',
    servings: 3,
    prepMinutes: 20,
    cookMinutes: 30,
    fridgeDays: 4,
    freezerDays: 90,
    eatCold: false,
    tags: ['spanisch', 'einfrieren', 'herzhaft', 'high-protein'],
    equipment: ['Herd', 'Backofen'],
    steps: [
      'Kartoffeln würfeln, mit Öl, Salz und Paprikapulver bei 220 °C 25–30 Minuten backen.',
      'Faschiertes mit Ei, Semmelbröseln, Knoblauch, Kreuzkümmel und Salz verkneten, walnussgroße Bällchen formen.',
      'Rundum scharf anbraten, herausnehmen.',
      'Zwiebel anschwitzen, Paprikapulver kurz mitrösten, Passata dazu, Bällchen hinein, 12 Minuten ziehen lassen.',
      'Mit Kräutern bestreuen.',
    ],
    per: [
      ['putenfaschiertes', 80],
      ['rinderfaschiertes', 50],
      ['eier', 10],
      ['semmelbroesel', 10],
      ['knoblauch', 3],
      ['kreuzkuemmel', 0.5],
      ['zwiebel', 30],
      ['passata', 150],
      ['paprikapulver', 3],
      ['olivenoel', 4],
      ['kartoffeln', 180],
      ['tk-kraeuter', 2],
    ],
  },
  {
    slug: 'haehnchen-paella',
    name: 'Hähnchen-Paella mit Paprika & Erbsen',
    mealType: 'main',
    description: 'Safrangelber Reis aus der Pfanne mit Hähnchen, Paprika, Erbsen und Rauchpaprika – kalt als Paella-Salat genauso gut wie warm.',
    flavorHack: 'Den Reis am Ende 2 Minuten ohne Rühren auf höherer Hitze lassen, bis es leise knistert – das ist der „Socarrat“, die knusprige Kruste am Pfannenboden.',
    servings: 3,
    prepMinutes: 15,
    cookMinutes: 30,
    fridgeDays: 4,
    freezerDays: 60,
    eatCold: true,
    tags: ['spanisch', 'kalt', 'einfrieren', 'one-pot', 'high-protein'],
    equipment: ['Herd'],
    steps: [
      'Hühnerbrust würfeln, salzen und in Olivenöl anbraten, herausnehmen.',
      'Zwiebel, Paprika und Knoblauch anschwitzen, Paprikapulver und Kurkuma kurz mitrösten.',
      'Reis und Tomaten dazu, mit 2,5-facher Menge Brühe aufgießen, 15 Minuten ohne Rühren köcheln.',
      'Huhn und Erbsen darauflegen, 5 Minuten fertig garen, zum Schluss kurz Kruste bilden lassen.',
      'Mit Zitronenspalten in Boxen füllen, Do/Fr-Portionen einfrieren.',
    ],
    per: [
      ['huehnerbrust', 125],
      ['reis', 55],
      ['paprika', 80],
      ['tk-erbsen', 50],
      ['zwiebel', 30],
      ['knoblauch', 3],
      ['tomaten-stueckig', 60],
      ['paprikapulver', 3],
      ['kurkuma', 1],
      ['gemuesebruehe', 3],
      ['olivenoel', 7],
      ['zitrone', 10],
    ],
  },
  {
    slug: 'protein-lasagne',
    name: 'Protein-Lasagne mit Hüttenkäse-Béchamel',
    mealType: 'main',
    description: 'Saftige Lasagne mit Rind-Linsen-Ragù, verstecktem Spinat und einer cremigen Hüttenkäse-Schicht statt Mehlschwitze – knusprig überbacken.',
    flavorHack: 'Hüttenkäse mit Ei, Muskat und etwas Milch glatt pürieren – wird im Ofen wie Béchamel, hat aber das Dreifache an Eiweiß.',
    servings: 4,
    prepMinutes: 20,
    cookMinutes: 45,
    fridgeDays: 4,
    freezerDays: 90,
    eatCold: false,
    tags: ['italienisch', 'ofen', 'einfrieren', 'high-protein'],
    equipment: ['Herd', 'Backofen'],
    steps: [
      'Zwiebel, Karotte und Knoblauch fein würfeln und anschwitzen, Faschiertes krümelig anbraten.',
      'Passata, Linsen, Oregano und 150 ml Wasser dazu, 15 Minuten köcheln, Spinat einrühren.',
      'Hüttenkäse mit Ei, Milch, Muskat und Salz pürieren.',
      'In der Form schichten: Ragù, Blätter, Hüttenkäse-Creme – dreimal, oben Creme und Mozzarella.',
      'Bei 190 °C 30 Minuten backen, 10 Minuten rasten lassen. Do/Fr-Portionen einfrieren.',
    ],
    per: [
      ['lasagneblaetter', 42],
      ['rinderfaschiertes', 60],
      ['rote-linsen', 20],
      ['passata', 150],
      ['zwiebel', 25],
      ['karotten', 30],
      ['knoblauch', 2],
      ['tk-spinat', 50],
      ['oregano', 1],
      ['huettenkaese', 90],
      ['eier', 10],
      ['milch', 30],
      ['mozzarella-light', 35],
    ],
  },

  // =================================================================== Wochenende
  {
    slug: 'haehnchen-saltimbocca',
    name: 'Hähnchen-Saltimbocca mit Zitronen-Kartoffeln & Zucchini',
    mealType: 'main',
    description: 'Dünne Hähnchenschnitzel mit Schinken und Salbei, in Zitronen-Butter-Sauce, dazu Zitronen-Kartoffeln und gebratene Zucchini – Trattoria zu Hause.',
    flavorHack: 'Nach dem Braten die Pfanne mit Zitronensaft und einem Schluck Wasser ablöschen, das Angebratene loskratzen und ein kleines Stück Butter einschwenken – fertig ist die Sauce.',
    servings: 1,
    prepMinutes: 10,
    cookMinutes: 20,
    fridgeDays: 2,
    freezerDays: 0,
    eatCold: false,
    tags: ['wochenende', 'italienisch', 'high-protein'],
    equipment: ['Herd'],
    steps: [
      'Kartoffeln kochen, halbieren und mit Zitronenabrieb und Salz anbraten.',
      'Hühnerbrust flach klopfen, mit Schinken und Salbei (Kräuter) belegen, leicht mehlieren.',
      'In Olivenöl je 3 Minuten pro Seite braten, herausnehmen.',
      'Mit Zitronensaft und Wasser ablöschen, Butter einschwenken, über das Fleisch geben.',
      'Zucchini in derselben Pfanne scharf anbraten.',
    ],
    per: [
      ['huehnerbrust', 160],
      ['putenschinken', 25],
      ['tk-kraeuter', 2],
      ['mehl', 5],
      ['olivenoel', 6],
      ['zitrone', 20],
      ['butter', 4],
      ['kartoffeln', 260],
      ['zucchini', 150],
    ],
  },
  {
    slug: 'tortilla-espanola',
    name: 'Tortilla española mit Paprika & Tomatensalat',
    mealType: 'main',
    description: 'Die spanische Kartoffel-Tortilla: saftig, dick, mit süßen Zwiebeln und Paprika – mit Hüttenkäse in der Eimasse extra eiweißreich. Dazu Tomatensalat.',
    flavorHack: 'Kartoffeln und Zwiebeln langsam in wenig Öl weich schmoren statt braten, und die Tortilla mit einem Teller wenden – innen bleibt sie cremig.',
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 25,
    fridgeDays: 3,
    freezerDays: 0,
    eatCold: true,
    tags: ['wochenende', 'spanisch', 'vegetarisch', 'kalt'],
    equipment: ['Herd'],
    steps: [
      'Kartoffeln in dünne Scheiben, Zwiebel und Paprika in Streifen schneiden, in Olivenöl zugedeckt 15 Minuten weich schmoren.',
      'Eier mit Hüttenkäse und Salz verquirlen, das Gemüse einrühren.',
      'Zurück in die Pfanne, bei kleiner Hitze 6 Minuten stocken lassen, mit einem Teller wenden, 3 Minuten fertig.',
      'Tomaten und Salat mit Balsamico und Salz anmachen.',
    ],
    per: [
      ['eier', 120],
      ['huettenkaese', 100],
      ['kartoffeln', 210],
      ['zwiebel', 60],
      ['paprika', 60],
      ['olivenoel', 6],
      ['tomaten', 100],
      ['eisberg', 40],
      ['balsamico', 5],
    ],
  },

  // =================================================================== Gönn-Essen Griechenland
  {
    slug: 'lammlachse-zitronenkartoffeln',
    name: 'Lammlachse mit Zitronen-Oregano-Kartoffeln & Bauernsalat',
    mealType: 'main',
    description: 'Zartes Lamm, rosa gebraten, dazu griechische Zitronenkartoffeln aus dem Ofen und ein Bauernsalat mit Feta. Das Gönn-Essen der griechischen Woche.',
    flavorHack: 'Die Kartoffeln mit Zitronensaft, Brühe, Knoblauch und Oregano im Ofen schmoren, bis die Flüssigkeit weg ist – außen knusprig, innen zitronig-saftig wie in der Taverne.',
    servings: 1,
    prepMinutes: 15,
    cookMinutes: 40,
    fridgeDays: 1,
    freezerDays: 0,
    eatCold: false,
    tags: ['goennung', 'wochenende', 'griechisch', 'high-protein'],
    equipment: ['Herd', 'Backofen'],
    steps: [
      'Kartoffeln in Spalten schneiden, mit Zitronensaft, 100 ml Brühe, Knoblauch, Oregano und der Hälfte des Öls bei 210 °C 35–40 Minuten schmoren.',
      'Lamm 30 Minuten vorher aus dem Kühlschrank nehmen, salzen, pfeffern.',
      'In der sehr heißen Pfanne rundum 6–8 Minuten braten, 5 Minuten rasten lassen, aufschneiden.',
      'Gurke, Tomate, Paprika und Zwiebel grob schneiden, mit Hirtenkäse, restlichem Öl und Oregano anmachen.',
    ],
    per: [
      ['lammlachse', 170],
      ['kartoffeln', 250],
      ['zitrone', 25],
      ['gemuesebruehe', 2],
      ['knoblauch', 4],
      ['oregano', 1.5],
      ['olivenoel', 10],
      ['gurke', 80],
      ['tomaten', 80],
      ['paprika', 50],
      ['zwiebel', 20],
      ['hirtenkaese', 25],
    ],
  },
];
