import type { MealType } from '../types';
import { SIMPLE_RECIPES } from './recipes-simple';
import { SOUTHERN_RECIPES } from './recipes-southern';
import { WEEKEND_RECIPES } from './recipes-weekend';

/**
 * The built-in recipes. Amounts are grams per portion – the seed multiplies them by
 * `servings`, so the stored recipe reads like a real batch ("520 g Hühnerbrust für 4").
 * Nutrition and cost are never typed in: they follow from the ingredients.
 */
export interface RecipeSeed {
  slug: string;
  name: string;
  mealType: MealType;
  description: string;
  flavorHack: string;
  servings: number;
  prepMinutes: number;
  cookMinutes: number;
  fridgeDays: number;
  freezerDays: number;
  eatCold: boolean;
  tags: string[];
  equipment: string[];
  steps: string[];
  per: [slug: string, grams: number, note?: string][];
}

const BASE_RECIPES: RecipeSeed[] = [
  // =================================================================== Frühstück
  {
    slug: 'overnight-oats-apfelstrudel',
    name: 'Overnight Oats Apfelstrudel',
    mealType: 'breakfast',
    description: 'Schmeckt wie Apfelstrudel mit Vanillesauce – wird am Vorabend in 3 Minuten angerührt, in der Früh nur noch umrühren.',
    flavorHack: 'Geriebenen Apfel mit Zimt und einer Prise Salz kurz in der Pfanne anrösten, bevor er ins Glas kommt – das karamellisiert und riecht nach Strudel.',
    servings: 1,
    prepMinutes: 3,
    cookMinutes: 0,
    fridgeDays: 2,
    freezerDays: 0,
    eatCold: true,
    tags: ['schnell', 'vorbereiten', 'süß', 'kalt', 'vegetarisch'],
    equipment: [],
    steps: [
      'Haferflocken, Skyr und Milch in einem Schraubglas verrühren.',
      'Apfel grob reiben, mit Zimt und Honig unterheben.',
      'Über Nacht in den Kühlschrank stellen.',
      'In der Früh umrühren und mit gehackten Mandeln bestreuen.',
    ],
    per: [
      ['haferflocken', 45],
      ['skyr', 180],
      ['milch', 100],
      ['apfel', 100],
      ['honig', 5],
      ['zimt', 1],
      ['mandeln', 15],
    ],
  },
  {
    slug: 'topfen-beeren-crunch',
    name: 'Topfen-Beeren-Crunch',
    mealType: 'breakfast',
    description: 'Cremiger Topfen, warme Beeren und knusprige Haferflocken mit Erdnussbutter – fertig in 4 Minuten.',
    flavorHack: 'TK-Beeren 60 Sekunden in einem Topf erwärmen: Sie werden zu einem schnellen Kompott und machen den Topfen süß, ohne extra Zucker.',
    servings: 1,
    prepMinutes: 4,
    cookMinutes: 1,
    fridgeDays: 1,
    freezerDays: 0,
    eatCold: true,
    tags: ['schnell', 'süß', 'high-protein', 'vegetarisch'],
    equipment: [],
    steps: [
      'Magertopfen mit einem Schuss Wasser glatt rühren.',
      'Beeren kurz erwärmen oder angetaut darübergeben.',
      'Haferflocken trocken in der Pfanne 1 Minute rösten.',
      'Mit Haferflocken, Honig und Erdnussbutter toppen.',
    ],
    per: [
      ['magertopfen', 200],
      ['tk-beeren', 90],
      ['haferflocken', 35],
      ['honig', 8],
      ['erdnussbutter', 18],
    ],
  },
  {
    slug: 'ruehrei-toast',
    name: 'Cremiges Rührei-Toast mit Paprika & Frühlingszwiebel',
    mealType: 'breakfast',
    description: 'Rührei, das durch Hüttenkäse fluffig bleibt, auf knusprigem Vollkornbrot.',
    flavorHack: 'Die Eier bei kleiner Hitze rühren und vom Herd nehmen, solange sie noch glänzen – dann Hüttenkäse und Kräuter unterziehen. Eine Prise Paprikapulver obendrauf.',
    servings: 1,
    prepMinutes: 2,
    cookMinutes: 4,
    fridgeDays: 0,
    freezerDays: 0,
    eatCold: false,
    tags: ['schnell', 'herzhaft', 'high-protein', 'vegetarisch'],
    equipment: ['Herd'],
    steps: [
      'Brot toasten, Paprika in Streifen schneiden.',
      'Eier mit Salz verquirlen, in wenig Öl bei kleiner Hitze stocken lassen.',
      'Vom Herd ziehen, Hüttenkäse und Kräuter unterheben.',
      'Auf dem Toast mit Paprika anrichten.',
    ],
    per: [
      ['eier', 120],
      ['huettenkaese', 60],
      ['vollkornbrot', 100],
      ['paprika', 60],
      ['rapsoel', 3],
      ['tk-kraeuter', 3],
      ['paprikapulver', 0.5],
      ['fruehlingszwiebel', 10],
      ['chiliflocken', 0.3],
    ],
  },
  {
    slug: 'schoko-bananen-porridge',
    name: 'Schoko-Bananen-Porridge',
    mealType: 'breakfast',
    description: 'Warmer Schokobrei mit Banane und Topfen – schmeckt nach Nachspeise, hält bis Mittag.',
    flavorHack: 'Eine Prise Salz und ein paar Tropfen Wasser zum Kakao geben, bevor die Milch dazukommt – so wird die Schokolade tiefer und klumpt nicht.',
    servings: 1,
    prepMinutes: 1,
    cookMinutes: 4,
    fridgeDays: 2,
    freezerDays: 0,
    eatCold: false,
    tags: ['schnell', 'süß', 'vegetarisch'],
    equipment: ['Herd'],
    steps: [
      'Haferflocken, Kakao und Milch in einem Topf aufkochen.',
      '3 Minuten unter Rühren köcheln lassen.',
      'Vom Herd nehmen, Magertopfen einrühren.',
      'Mit Bananenscheiben und Erdnüssen servieren.',
    ],
    per: [
      ['haferflocken', 40],
      ['milch', 200],
      ['kakao', 8],
      ['banane', 60],
      ['magertopfen', 130],
      ['erdnuesse', 10],
    ],
  },
  {
    slug: 'skyr-becher-to-go',
    name: 'Skyr-Becher to go',
    mealType: 'breakfast',
    description: 'Skyr, Haferflocken, Banane und Erdnüsse im Becher – zum Mitnehmen, wenn es in der Früh schnell gehen muss.',
    flavorHack: 'Die Banane mit der Gabel zerdrücken und unter den Skyr rühren – süßt den ganzen Becher gleichmäßig.',
    servings: 1,
    prepMinutes: 2,
    cookMinutes: 0,
    fridgeDays: 1,
    freezerDays: 0,
    eatCold: true,
    tags: ['schnell', 'kalt', 'transportfähig', 'süß', 'vegetarisch'],
    equipment: [],
    steps: ['Banane zerdrücken und mit Skyr verrühren.', 'Haferflocken und Honig untermischen.', 'Mit Erdnüssen toppen, Deckel drauf.'],
    per: [
      ['skyr', 200],
      ['haferflocken', 30],
      ['banane', 90],
      ['honig', 5],
      ['erdnuesse', 20],
    ],
  },
  {
    slug: 'schinken-kaese-wrap',
    name: 'Schinken-Käse-Frühstückswrap mit Apfel',
    mealType: 'breakfast',
    description: 'Wrap mit Hüttenkäse, Putenschinken, Käse und Gurke – in 3 Minuten gerollt, kalt zu essen.',
    flavorHack: 'Den Wrap mit Senf-Hüttenkäse bestreichen und in einer trockenen Pfanne 30 Sekunden pro Seite anrösten – knusprig und der Käse schmilzt an.',
    servings: 1,
    prepMinutes: 3,
    cookMinutes: 1,
    fridgeDays: 1,
    freezerDays: 0,
    eatCold: true,
    tags: ['schnell', 'kalt', 'transportfähig', 'herzhaft'],
    equipment: [],
    steps: [
      'Hüttenkäse mit Senf verrühren und auf den Wrap streichen.',
      'Schinken, Käse und Gurkenscheiben darauflegen.',
      'Fest einrollen, halbieren. Apfel dazu.',
    ],
    per: [
      ['wraps', 62],
      ['putenschinken', 70],
      ['kaese-light', 25],
      ['huettenkaese', 60],
      ['gurke', 60],
      ['senf', 5],
      ['apfel', 80],
    ],
  },
  {
    slug: 'huettenkaese-brot-ei',
    name: 'Hüttenkäse-Brot mit Ei & Tomate',
    mealType: 'breakfast',
    description: 'Zwei Scheiben Vollkornbrot mit Kräuter-Hüttenkäse, einem vorgekochten Ei und Tomate.',
    flavorHack: 'Tomatenscheiben salzen und 2 Minuten liegen lassen – sie werden saftiger. Dazu Pfeffer und ein paar Tropfen Olivenöl.',
    servings: 1,
    prepMinutes: 4,
    cookMinutes: 0,
    fridgeDays: 1,
    freezerDays: 0,
    eatCold: true,
    tags: ['schnell', 'kalt', 'herzhaft', 'vegetarisch'],
    equipment: [],
    steps: [
      'Eier werden beim Sonntags-Prep mitgekocht (9 Minuten, dann kalt abschrecken).',
      'Hüttenkäse mit Kräutern, Salz und Pfeffer verrühren.',
      'Brot bestreichen, mit Ei- und Tomatenscheiben belegen, Olivenöl darüber.',
    ],
    per: [
      ['vollkornbrot', 90],
      ['huettenkaese', 120],
      ['eier', 60],
      ['tomaten', 100],
      ['olivenoel', 3],
      ['tk-kraeuter', 3],
    ],
  },
  {
    slug: 'protein-pancakes',
    name: 'Protein-Pancakes mit Beeren',
    mealType: 'breakfast',
    description: 'Fluffige Topfen-Hafer-Pancakes ohne Mixer – das Wochenend-Frühstück.',
    flavorHack: 'Teig 5 Minuten quellen lassen und die Pfanne erst heiß werden lassen – dann gehen die Pancakes richtig auf. Beeren kurz in der Pfanne erhitzen und als Sauce darüber.',
    servings: 1,
    prepMinutes: 5,
    cookMinutes: 8,
    fridgeDays: 2,
    freezerDays: 30,
    eatCold: false,
    tags: ['wochenende', 'süß', 'high-protein', 'vegetarisch'],
    equipment: ['Herd'],
    steps: [
      'Banane zerdrücken, mit Ei, Magertopfen und Milch verrühren.',
      'Haferflocken einrühren, 5 Minuten quellen lassen.',
      'In wenig Öl kleine Pancakes bei mittlerer Hitze je 2 Minuten pro Seite backen.',
      'Beeren erhitzen, mit Honig über die Pancakes geben.',
    ],
    per: [
      ['haferflocken', 50],
      ['eier', 60],
      ['magertopfen', 125],
      ['banane', 60],
      ['milch', 30],
      ['tk-beeren', 80],
      ['rapsoel', 4],
      ['honig', 5],
    ],
  },
  {
    slug: 'chia-skyr-pudding',
    name: 'Chia-Skyr-Pudding mit Beeren',
    mealType: 'breakfast',
    description: 'Am Vorabend angerührt, in der Früh cremig wie Pudding – mit Beeren und Mandeln.',
    flavorHack: 'Chia zuerst nur mit der Milch 10 Minuten quellen lassen und dann den Skyr unterrühren – so wird es cremig statt glibberig.',
    servings: 1,
    prepMinutes: 3,
    cookMinutes: 0,
    fridgeDays: 2,
    freezerDays: 0,
    eatCold: true,
    tags: ['vorbereiten', 'kalt', 'transportfähig', 'süß', 'vegetarisch'],
    equipment: [],
    steps: [
      'Chiasamen mit Milch verrühren und 10 Minuten quellen lassen.',
      'Skyr, Haferflocken und Honig unterrühren, über Nacht kühlen.',
      'Mit aufgetauten Beeren und Mandeln toppen.',
    ],
    per: [
      ['skyr', 200],
      ['chiasamen', 15],
      ['milch', 100],
      ['tk-beeren', 100],
      ['haferflocken', 20],
      ['honig', 6],
      ['mandeln', 10],
    ],
  },

  {
    slug: 'bircher-muesli',
    name: 'Bircher-Müsli mit Skyr & Apfel',
    mealType: 'breakfast',
    description: 'Der Schweizer Klassiker, eiweißreich: über Nacht gequollene Haferflocken mit frisch geriebenem Apfel, Zitrone, Skyr und gerösteten Mandeln.',
    flavorHack: 'Den Apfel erst in der Früh grob dazureiben und mit ein paar Tropfen Zitrone mischen – er bleibt knackig und frisch, das Müsli wird nicht grau.',
    servings: 1,
    prepMinutes: 4,
    cookMinutes: 0,
    fridgeDays: 2,
    freezerDays: 0,
    eatCold: true,
    tags: ['vorbereiten', 'kalt', 'transportfähig', 'süß', 'vegetarisch'],
    equipment: [],
    steps: [
      'Am Vorabend Haferflocken mit Milch und der Hälfte des Skyrs verrühren, zugedeckt kühlen.',
      'In der Früh Apfel grob dazureiben, Zitronensaft, Zimt und restlichen Skyr unterrühren.',
      'Mandeln trocken anrösten, grob hacken und darüberstreuen, Honig drüber.',
    ],
    per: [
      ['haferflocken', 45],
      ['skyr', 200],
      ['milch', 80],
      ['apfel', 120],
      ['zitrone', 5],
      ['zimt', 0.5],
      ['mandeln', 10],
      ['honig', 5],
    ],
  },

  // =================================================================== Jausen & Snacks
  {
    slug: 'thunfisch-mais-wrap',
    name: 'Thunfisch-Mais-Wrap',
    mealType: 'snack',
    description: 'Cremiger Thunfisch mit Mais und Paprika im Wrap – hält gut bis zur großen Pause.',
    flavorHack: 'Thunfisch mit Skyr, Senf, Zitronensaft und viel Pfeffer anmachen – schmeckt wie Thunfischsalat aus dem Feinkostregal, nur mit dreimal so viel Eiweiß.',
    servings: 1,
    prepMinutes: 5,
    cookMinutes: 0,
    fridgeDays: 1,
    freezerDays: 0,
    eatCold: true,
    tags: ['kalt', 'transportfähig', 'high-protein', 'budget'],
    equipment: [],
    steps: [
      'Thunfisch abtropfen, mit Skyr, Senf und Zitronensaft verrühren, pfeffern.',
      'Mais und Paprikawürfel unterheben.',
      'Auf den Wrap streichen, fest einrollen und in Alufolie wickeln.',
    ],
    per: [
      ['wraps', 62],
      ['thunfisch', 75],
      ['skyr', 30],
      ['mais', 30],
      ['paprika', 40],
      ['senf', 5],
      ['zitrone', 5],
      ['olivenoel', 7],
      ['fruehlingszwiebel', 5],
    ],
  },
  {
    slug: 'huehner-club-sandwich',
    name: 'Hühner-Club-Sandwich',
    mealType: 'snack',
    description: 'Vollkornbrot mit Hühnerbrust vom Sonntag, Senf-Hüttenkäse, Tomate und Salat.',
    flavorHack: 'Das Hühnerfleisch dünn aufschneiden und mit einem Tropfen Sojasauce und Pfeffer marinieren – so schmeckt es nicht nach Meal Prep.',
    servings: 1,
    prepMinutes: 4,
    cookMinutes: 0,
    fridgeDays: 1,
    freezerDays: 0,
    eatCold: true,
    tags: ['kalt', 'transportfähig', 'high-protein'],
    equipment: [],
    steps: [
      'Hühnerbrust wird am Sonntag mitgegart (siehe Prep-Ablauf).',
      'Brot mit Senf-Hüttenkäse bestreichen.',
      'Mit Hühnerbrust, Tomate und Salat belegen, zuklappen, halbieren.',
    ],
    per: [
      ['vollkornbrot', 100],
      ['huehnerbrust', 80, 'gegart'],
      ['huettenkaese', 40],
      ['tomaten', 40],
      ['eisberg', 20],
      ['senf', 5],
      ['mayonnaise', 6],
    ],
  },
  {
    slug: 'kraeuter-topfen-dip',
    name: 'Kräuter-Topfen-Dip mit Gemüse & Reiswaffeln',
    mealType: 'snack',
    description: 'Knoblauch-Kräuter-Topfen zum Dippen, dazu Karotten, Gurke, Paprika und Reiswaffeln.',
    flavorHack: 'Den Knoblauch fein reiben und mit Olivenöl und Salz verrühren, bevor der Topfen dazukommt – so verteilt sich das Aroma, ohne scharf zu sein.',
    servings: 1,
    prepMinutes: 6,
    cookMinutes: 0,
    fridgeDays: 2,
    freezerDays: 0,
    eatCold: true,
    tags: ['kalt', 'transportfähig', 'vegetarisch', 'budget'],
    equipment: [],
    steps: [
      'Knoblauch reiben, mit Olivenöl, Salz und Kräutern verrühren.',
      'Magertopfen glatt rühren und unterheben.',
      'Gemüse in Sticks schneiden, alles in eine Box. Reiswaffeln separat einpacken.',
    ],
    per: [
      ['magertopfen', 200],
      ['olivenoel', 10],
      ['tk-kraeuter', 3],
      ['knoblauch', 3],
      ['karotten', 100],
      ['gurke', 100],
      ['paprika', 60],
      ['reiswaffeln', 11],
    ],
  },
  {
    slug: 'gemuese-eier-muffins',
    name: 'Gemüse-Eier-Muffins mit Vollkornbrot',
    mealType: 'snack',
    description: 'Drei saftige Ei-Muffins mit Spinat, Paprika und Käse plus eine Scheibe Brot – einmal backen, eine Woche Jause.',
    flavorHack: 'Eine Prise geräuchertes Paprikapulver und etwas Senf in die Eimasse – die Muffins schmecken dann nach Speck, ganz ohne Speck.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 20,
    fridgeDays: 4,
    freezerDays: 60,
    eatCold: true,
    tags: ['kalt', 'transportfähig', 'vorbereiten', 'einfrieren', 'vegetarisch'],
    equipment: ['Backofen'],
    steps: [
      'Backofen auf 180 °C Umluft vorheizen, Muffinform einfetten.',
      'Eier mit Hüttenkäse, Senf, Paprikapulver, Salz und Pfeffer verquirlen.',
      'Aufgetauten Spinat ausdrücken, mit Paprikawürfeln auf 12 Mulden verteilen.',
      'Eimasse darübergießen, Käse darüberzupfen, 20 Minuten backen.',
      'Auskühlen lassen, je 3 Stück pro Box. Für Do/Fr einfrieren.',
    ],
    per: [
      ['eier', 90],
      ['huettenkaese', 70],
      ['tk-spinat', 40],
      ['paprika', 40],
      ['kaese-light', 15],
      ['senf', 2],
      ['paprikapulver', 0.5],
      ['vollkornbrot', 50],
    ],
  },
  {
    slug: 'huehner-couscous-salat',
    name: 'Hühner-Couscous-Salat im Glas',
    mealType: 'snack',
    description: 'Zitroniger Couscous mit Hühnerbrust, Gurke, Tomate und Hirtenkäse – geschichtet, damit nichts matschig wird.',
    flavorHack: 'Den Couscous mit heißer Gemüsebrühe statt Wasser quellen lassen und Zitronenabrieb dazu – das ist der ganze Unterschied.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 5,
    fridgeDays: 3,
    freezerDays: 0,
    eatCold: true,
    tags: ['kalt', 'transportfähig', 'mediterran'],
    equipment: ['Herd'],
    steps: [
      'Couscous mit der gleichen Menge heißer Brühe übergießen, 5 Minuten quellen lassen.',
      'Mit Zitronensaft, Olivenöl und Kräutern auflockern.',
      'In Gläser schichten: Dressing-Couscous unten, dann Huhn, Gemüse, Hirtenkäse oben.',
    ],
    per: [
      ['couscous', 35],
      ['huehnerbrust', 80, 'gegart'],
      ['gurke', 60],
      ['tomaten', 60],
      ['hirtenkaese', 17],
      ['zitrone', 15],
      ['olivenoel', 10],
      ['tk-kraeuter', 3],
      ['gemuesebruehe', 2],
    ],
  },
  {
    slug: 'chicken-caesar-wrap',
    name: 'Chicken-Caesar-Wrap',
    mealType: 'snack',
    description: 'Knackiger Salat, Hühnerbrust und ein leichtes Caesar-Dressing aus Skyr, Senf und Knoblauch.',
    flavorHack: 'Dressing aus Skyr, Senf, Zitrone, geriebenem Knoblauch und fein geriebenem Käse – schmeckt fast wie das Original mit Parmesan.',
    servings: 1,
    prepMinutes: 5,
    cookMinutes: 0,
    fridgeDays: 1,
    freezerDays: 0,
    eatCold: true,
    tags: ['kalt', 'transportfähig', 'high-protein'],
    equipment: [],
    steps: [
      'Skyr mit Senf, Zitronensaft, Knoblauch und fein geriebenem Käse verrühren.',
      'Salat in Streifen schneiden, Hühnerbrust aufschneiden.',
      'Alles auf den Wrap, Dressing darüber, fest einrollen.',
    ],
    per: [
      ['wraps', 62],
      ['huehnerbrust', 75, 'gegart'],
      ['eisberg', 30],
      ['skyr', 30],
      ['senf', 5],
      ['kaese-light', 10],
      ['zitrone', 5],
      ['knoblauch', 2],
      ['olivenoel', 5],
    ],
  },
  {
    slug: 'kichererbsen-thunfisch-salat',
    name: 'Kichererbsen-Thunfisch-Salat',
    mealType: 'snack',
    description: 'Mediterraner Bohnen-Salat mit Thunfisch, Paprika und Hirtenkäse, dazu zwei Reiswaffeln.',
    flavorHack: 'Die Zwiebel in feine Ringe schneiden und 5 Minuten in Zitronensaft und Salz ziehen lassen – mild, knackig und leicht rosa.',
    servings: 2,
    prepMinutes: 8,
    cookMinutes: 0,
    fridgeDays: 3,
    freezerDays: 0,
    eatCold: true,
    tags: ['kalt', 'transportfähig', 'mediterran', 'budget'],
    equipment: [],
    steps: [
      'Zwiebel in Zitronensaft und Salz einlegen.',
      'Kichererbsen abspülen, Gemüse würfeln.',
      'Alles mit Thunfisch, Olivenöl und Oregano mischen, Hirtenkäse darüberbröseln.',
    ],
    per: [
      ['kichererbsen', 80],
      ['thunfisch', 70],
      ['paprika', 50],
      ['gurke', 60],
      ['zwiebel', 15],
      ['olivenoel', 9],
      ['zitrone', 15],
      ['hirtenkaese', 10],
      ['oregano', 0.5],
      ['reiswaffeln', 15],
    ],
  },
  {
    slug: 'skyr-apfel-erdnuss',
    name: 'Zimt-Skyr mit Apfel & Erdnüssen',
    mealType: 'snack',
    description: 'Skyr mit Zimt, Apfelstücken und gerösteten Erdnüssen – eiweißreich und knackig.',
    flavorHack: 'Die Erdnüsse mit einer Prise Salz in der trockenen Pfanne anrösten – salzig-süß macht den Unterschied.',
    servings: 1,
    prepMinutes: 3,
    cookMinutes: 0,
    fridgeDays: 1,
    freezerDays: 0,
    eatCold: true,
    tags: ['kalt', 'transportfähig', 'ruhetag', 'schnell', 'vegetarisch'],
    equipment: [],
    steps: ['Skyr mit Zimt verrühren.', 'Apfel würfeln und darübergeben.', 'Mit Erdnüssen toppen.'],
    per: [
      ['skyr', 100],
      ['apfel', 130],
      ['erdnuesse', 20],
      ['zimt', 1],
    ],
  },
  {
    slug: 'low-carb-snackbox',
    name: 'Low-Carb-Snackbox',
    mealType: 'snack',
    description: 'Ein Ei, Käse, Mandeln und viel knackiges Gemüse – für Ruhetage, an denen die Kohlenhydrate kleiner ausfallen.',
    flavorHack: 'Gemüse mit Salz, Pfeffer und ein paar Tropfen Zitronensaft marinieren – schmeckt wie ein Salat zum Mitnehmen.',
    servings: 1,
    prepMinutes: 4,
    cookMinutes: 0,
    fridgeDays: 2,
    freezerDays: 0,
    eatCold: true,
    tags: ['kalt', 'transportfähig', 'ruhetag', 'vegetarisch'],
    equipment: [],
    steps: ['Ei aus dem Sonntags-Prep schälen und halbieren.', 'Gemüse in Sticks schneiden.', 'Mit Käse und Mandeln in eine Box packen.'],
    per: [
      ['eier', 60],
      ['kaese-light', 10],
      ['gurke', 100],
      ['paprika', 80],
      ['karotten', 80],
      ['mandeln', 12],
      ['zitrone', 5],
    ],
  },
  {
    slug: 'hummus-gemuesesticks',
    name: 'Hummus mit Gemüsesticks & Erdnüssen',
    mealType: 'snack',
    description: 'Schneller Hummus aus Kichererbsen mit Kreuzkümmel, dazu Gemüse zum Dippen.',
    flavorHack: 'Ein Eiswürfel in den Mixer – der Hummus wird hell und fluffig wie im Restaurant. Ohne Mixer: mit der Gabel zerdrücken, dann rustikal.',
    servings: 2,
    prepMinutes: 7,
    cookMinutes: 0,
    fridgeDays: 4,
    freezerDays: 30,
    eatCold: true,
    tags: ['kalt', 'transportfähig', 'ruhetag', 'vegetarisch', 'budget'],
    equipment: [],
    steps: [
      'Kichererbsen mit Olivenöl, Zitronensaft, Knoblauch, Kreuzkümmel und Salz pürieren oder zerdrücken.',
      'Gemüse in Sticks schneiden.',
      'Hummus in eine Box, Erdnüsse darüber, Gemüse daneben.',
    ],
    per: [
      ['kichererbsen', 80],
      ['olivenoel', 6],
      ['zitrone', 10],
      ['knoblauch', 2],
      ['kreuzkuemmel', 1],
      ['karotten', 80],
      ['paprika', 80],
      ['gurke', 80],
      ['erdnuesse', 8],
    ],
  },
  {
    slug: 'apfel-erdnussbutter-kaese',
    name: 'Apfelschnitze mit Erdnussbutter & Käse',
    mealType: 'snack',
    description: 'Apfelspalten zum Eintunken in Erdnussbutter, dazu zwei Scheiben Käse.',
    flavorHack: 'Eine Prise Zimt und Salz in die Erdnussbutter rühren – schmeckt wie Karamell.',
    servings: 1,
    prepMinutes: 2,
    cookMinutes: 0,
    fridgeDays: 1,
    freezerDays: 0,
    eatCold: true,
    tags: ['kalt', 'transportfähig', 'ruhetag', 'schnell', 'vegetarisch'],
    equipment: [],
    steps: ['Apfel in Spalten schneiden, mit Zitronensaft beträufeln.', 'Erdnussbutter mit Zimt in ein kleines Glas.', 'Käse dazupacken.'],
    per: [
      ['apfel', 180],
      ['erdnussbutter', 18],
      ['kaese-light', 20],
      ['zimt', 0.5],
    ],
  },

  // =================================================================== Pre-Workout
  {
    slug: 'reiswaffeln-banane-honig',
    name: 'Reiswaffeln mit Topfen, Banane & Honig',
    mealType: 'preworkout',
    description: 'Schnelle Kohlenhydrate und etwas Eiweiß, liegt nicht schwer im Magen.',
    flavorHack: 'Eine Prise Salz auf den Honig – hilft beim Schwitzen und schmeckt nach Salted Caramel.',
    servings: 1,
    prepMinutes: 2,
    cookMinutes: 0,
    fridgeDays: 0,
    freezerDays: 0,
    eatCold: true,
    tags: ['training', 'schnell', 'süß', 'vegetarisch'],
    equipment: [],
    steps: ['Reiswaffeln mit Magertopfen bestreichen.', 'Bananenscheiben darauflegen.', 'Mit Honig beträufeln, eine Prise Salz.'],
    per: [
      ['reiswaffeln', 22.5],
      ['magertopfen', 90],
      ['banane', 120],
      ['honig', 10],
    ],
  },
  {
    slug: 'bananen-hafer-riegel',
    name: 'Bananen-Hafer-Riegel',
    mealType: 'preworkout',
    description: 'Weiche Riegel aus Haferflocken, Banane, Honig und Erdnussbutter – am Sonntag gebacken, reicht für die Woche.',
    flavorHack: 'Die Haferflocken vorher 5 Minuten im Ofen rösten – die Riegel schmecken dann nach Keks statt nach Porridge.',
    servings: 8,
    prepMinutes: 10,
    cookMinutes: 22,
    fridgeDays: 6,
    freezerDays: 60,
    eatCold: true,
    tags: ['training', 'vorbereiten', 'einfrieren', 'transportfähig', 'süß', 'vegetarisch'],
    equipment: ['Backofen'],
    steps: [
      'Backofen auf 180 °C vorheizen, Haferflocken 5 Minuten rösten.',
      'Bananen zerdrücken, mit Ei, Honig, Erdnussbutter und Zimt verrühren.',
      'Haferflocken untermischen, in eine mit Backpapier ausgelegte Form drücken.',
      '20 Minuten backen, auskühlen lassen, in 8 Riegel schneiden.',
    ],
    per: [
      ['haferflocken', 40],
      ['banane', 40],
      ['honig', 10],
      ['erdnussbutter', 6],
      ['eier', 7.5],
      ['zimt', 0.5],
    ],
  },
  {
    slug: 'beeren-skyr-honig',
    name: 'Beeren-Skyr mit Honig & Hafer',
    mealType: 'preworkout',
    description: 'Leichter Beeren-Skyr mit Honig und ein paar Haferflocken – frisch und schnell verdaulich.',
    flavorHack: 'Die Beeren halb antauen lassen und mit dem Honig zerdrücken – gibt eine natürliche Fruchtsauce.',
    servings: 1,
    prepMinutes: 2,
    cookMinutes: 0,
    fridgeDays: 1,
    freezerDays: 0,
    eatCold: true,
    tags: ['training', 'schnell', 'süß', 'kalt', 'vegetarisch'],
    equipment: [],
    steps: ['Beeren mit Honig zerdrücken.', 'Skyr darübergeben.', 'Mit Haferflocken bestreuen.'],
    per: [
      ['skyr', 90],
      ['tk-beeren', 120],
      ['honig', 15],
      ['haferflocken', 25],
    ],
  },
  {
    slug: 'honig-topfen-brot',
    name: 'Honig-Topfen-Brot mit Banane',
    mealType: 'preworkout',
    description: 'Das klassische Butterbrot, nur mit Topfen und Honig – ideal, wenn es direkt nach der Schule schnell gehen muss.',
    flavorHack: 'Das Brot kurz toasten, dann schmilzt der Honig in den Topfen.',
    servings: 1,
    prepMinutes: 2,
    cookMinutes: 1,
    fridgeDays: 0,
    freezerDays: 0,
    eatCold: true,
    tags: ['training', 'schnell', 'süß', 'vegetarisch', 'budget'],
    equipment: [],
    steps: ['Brot toasten.', 'Mit Magertopfen bestreichen, Honig darüber.', 'Banane dazu essen.'],
    per: [
      ['vollkornbrot', 75],
      ['magertopfen', 90],
      ['honig', 15],
      ['banane', 40],
    ],
  },
  {
    slug: 'zimt-milchreis',
    name: 'Zimt-Milchreis mit Apfel',
    mealType: 'preworkout',
    description: 'Cremiger Milchreis wie von der Oma, am Sonntag für 4 Tage gekocht – kalt oder warm.',
    flavorHack: 'Eine Prise Salz und ein Stück Zitronenschale mitkochen – das macht den Geschmack „wie früher“.',
    servings: 4,
    prepMinutes: 5,
    cookMinutes: 30,
    fridgeDays: 4,
    freezerDays: 0,
    eatCold: true,
    tags: ['training', 'vorbereiten', 'süß', 'österreichisch', 'vegetarisch', 'budget'],
    equipment: ['Herd'],
    steps: [
      'Milch mit Milchreis, Zitronenschale und einer Prise Salz aufkochen.',
      'Bei kleinster Hitze 30 Minuten zugedeckt ziehen lassen, ab und zu umrühren.',
      'Honig und Zimt einrühren, in 4 Gläser füllen.',
      'Vor dem Essen mit geriebenem Apfel toppen.',
    ],
    per: [
      ['milchreis', 40],
      ['milch', 200],
      ['honig', 10],
      ['zimt', 1],
      ['apfel', 50],
      ['zitrone', 5],
    ],
  },
  {
    slug: 'banana-oat-shake',
    name: 'Banana-Oat-Shake',
    mealType: 'preworkout',
    description: 'Milch, Banane, Haferflocken und Honig im Mixer – trinkbar auf dem Weg zum Training.',
    flavorHack: 'Die Banane gefroren verwenden – der Shake wird dick wie ein Milchshake.',
    servings: 1,
    prepMinutes: 3,
    cookMinutes: 0,
    fridgeDays: 1,
    freezerDays: 0,
    eatCold: true,
    tags: ['training', 'schnell', 'süß', 'vegetarisch'],
    equipment: ['Mixer'],
    steps: ['Alles in den Mixer.', '30 Sekunden mixen.', 'In eine Flasche füllen.'],
    per: [
      ['milch', 250],
      ['banane', 100],
      ['haferflocken', 25],
      ['honig', 5],
    ],
  },

  // =================================================================== Saucen & Marinaden
  {
    slug: 'knoblauch-skyr-tzatziki',
    name: 'Knoblauch-Skyr-Tzatziki',
    mealType: 'sauce',
    description: 'Basis Skyr-Joghurt: klassisches Tzatziki mit geraspelter Gurke und viel Knoblauch.',
    flavorHack: 'Die geraspelte Gurke salzen und 10 Minuten später kräftig ausdrücken – das Tzatziki bleibt dann 4 Tage dick.',
    servings: 6,
    prepMinutes: 8,
    cookMinutes: 0,
    fridgeDays: 4,
    freezerDays: 0,
    eatCold: true,
    tags: ['basis-skyr', 'kalt', 'mediterran'],
    equipment: [],
    steps: ['Gurke raspeln, salzen, nach 10 Minuten ausdrücken.', 'Mit Skyr, geriebenem Knoblauch, Olivenöl und Zitronensaft verrühren.', 'Abschmecken, in ein Glas füllen.'],
    per: [
      ['skyr', 40],
      ['gurke', 20],
      ['knoblauch', 1.5],
      ['olivenoel', 2],
      ['zitrone', 3],
    ],
  },
  {
    slug: 'sriracha-skyr-mayo',
    name: 'Sriracha-Skyr-Mayo',
    mealType: 'sauce',
    description: 'Basis Skyr-Joghurt: scharf-cremig, zu Ofenhuhn, Wedges und Bowls.',
    flavorHack: 'Nur ein Löffel echte Mayo reicht, damit sie nach Burgersauce schmeckt – der Rest ist Skyr.',
    servings: 6,
    prepMinutes: 3,
    cookMinutes: 0,
    fridgeDays: 5,
    freezerDays: 0,
    eatCold: true,
    tags: ['basis-skyr', 'kalt', 'scharf'],
    equipment: [],
    steps: ['Skyr, Mayonnaise, Sriracha und Zitronensaft glatt rühren.', 'Mit Salz abschmecken, in ein Glas füllen.'],
    per: [
      ['skyr', 30],
      ['mayonnaise', 6],
      ['sriracha', 6],
      ['zitrone', 2],
    ],
  },
  {
    slug: 'scharfe-paprika-skyr-mayo',
    name: 'Scharfe Paprika-Skyr-Mayo',
    mealType: 'sauce',
    description: 'Basis Skyr-Joghurt: rauchig-scharf wie die Sauce auf Patatas bravas – zu Ofenhuhn, Wedges und Gyros-Bowls.',
    flavorHack: 'Geräuchertes Paprikapulver nehmen, nicht edelsüß – das bringt den Grill-Geschmack. Eine halbe Stunde ziehen lassen, dann verbinden sich Knoblauch und Chili.',
    servings: 6,
    prepMinutes: 3,
    cookMinutes: 0,
    fridgeDays: 5,
    freezerDays: 0,
    eatCold: true,
    tags: ['basis-skyr', 'kalt', 'scharf'],
    equipment: [],
    steps: ['Skyr, Mayonnaise, Paprikapulver, Chiliflocken, gepressten Knoblauch und Zitronensaft glatt rühren.', 'Mit Salz abschmecken, in ein Glas füllen.'],
    per: [
      ['skyr', 30],
      ['mayonnaise', 6],
      ['paprikapulver', 1.5],
      ['chiliflocken', 0.3],
      ['knoblauch', 1],
      ['zitrone', 2],
    ],
  },
  {
    slug: 'curry-honig-dip',
    name: 'Curry-Honig-Dip',
    mealType: 'sauce',
    description: 'Basis Skyr-Joghurt: süß-würzig, passt zu Kofta, Couscous und Wraps.',
    flavorHack: 'Das Currypulver 20 Sekunden in einem Tropfen Öl anrösten, bevor es in den Skyr kommt – schmeckt doppelt so intensiv.',
    servings: 6,
    prepMinutes: 3,
    cookMinutes: 1,
    fridgeDays: 5,
    freezerDays: 0,
    eatCold: true,
    tags: ['basis-skyr', 'kalt'],
    equipment: [],
    steps: ['Currypulver kurz in wenig Öl anrösten.', 'Mit Skyr, Honig und Zitronensaft verrühren.'],
    per: [
      ['skyr', 35],
      ['currypulver', 1],
      ['honig', 4],
      ['zitrone', 2],
      ['rapsoel', 0.5],
    ],
  },
  {
    slug: 'teriyaki-glaze',
    name: 'Teriyaki-Glaze',
    mealType: 'sauce',
    description: 'Basis Soja-Ingwer: glänzende, süß-salzige Glasur für Huhn und Reis.',
    flavorHack: 'Erst in der Pfanne einkochen, bis sie Blasen wirft und am Löffel hängen bleibt – dann klebt sie am Fleisch statt am Boden der Box.',
    servings: 6,
    prepMinutes: 3,
    cookMinutes: 4,
    fridgeDays: 7,
    freezerDays: 60,
    eatCold: true,
    tags: ['basis-soja', 'asia'],
    equipment: ['Herd'],
    steps: [
      'Sojasauce, Honig, geriebenen Ingwer und Knoblauch mit 60 ml Wasser aufkochen.',
      'Maisstärke mit etwas kaltem Wasser anrühren und einrühren.',
      '1–2 Minuten köcheln, bis es glänzt. Sesam darüber.',
    ],
    per: [
      ['sojasauce', 15],
      ['honig', 8],
      ['ingwer', 2],
      ['knoblauch', 1.5],
      ['maisstaerke', 2],
      ['sesam', 1],
    ],
  },
  {
    slug: 'erdnuss-zitronen-sauce',
    name: 'Erdnuss-Zitronen-Sauce',
    mealType: 'sauce',
    description: 'Basis Soja-Ingwer: cremige Satay-Sauce für kalte Nudeln und Bowls.',
    flavorHack: 'Mit heißem Wasser glatt rühren statt mit kaltem – dann wird sie seidig und dickt im Kühlschrank nicht zu stark ein.',
    servings: 6,
    prepMinutes: 4,
    cookMinutes: 0,
    fridgeDays: 5,
    freezerDays: 0,
    eatCold: true,
    tags: ['basis-soja', 'asia', 'kalt'],
    equipment: [],
    steps: ['Erdnussbutter mit 3 EL heißem Wasser glatt rühren.', 'Sojasauce, Zitronensaft, Sriracha, Honig und Ingwer einrühren.', 'Sauce soll dickflüssig sein – bei Bedarf Wasser nachgeben.'],
    per: [
      ['erdnussbutter', 12],
      ['sojasauce', 8],
      ['zitrone', 5],
      ['sriracha', 3],
      ['honig', 3],
      ['ingwer', 1],
    ],
  },
  {
    slug: 'sweet-chili-soja',
    name: 'Sweet-Chili-Soja-Dressing',
    mealType: 'sauce',
    description: 'Basis Soja-Ingwer: süß-scharf-sauer, perfekt für Rindfleisch und Brokkoli.',
    flavorHack: 'Sesam in der trockenen Pfanne rösten, bis er duftet – gibt dem Dressing Röstaroma.',
    servings: 6,
    prepMinutes: 3,
    cookMinutes: 1,
    fridgeDays: 7,
    freezerDays: 0,
    eatCold: true,
    tags: ['basis-soja', 'asia', 'scharf', 'kalt'],
    equipment: [],
    steps: ['Sesam rösten.', 'Sojasauce, Sriracha, Honig, Essig und Knoblauch verrühren.', 'Sesam untermischen.'],
    per: [
      ['sojasauce', 10],
      ['sriracha', 5],
      ['honig', 6],
      ['essig', 5],
      ['sesam', 2],
      ['knoblauch', 1],
    ],
  },
  {
    slug: 'pico-salsa',
    name: 'Pico-de-Gallo-Salsa',
    mealType: 'sauce',
    description: 'Basis Tomate: frische Salsa aus Tomate, Zwiebel, Zitrone und Chili.',
    flavorHack: 'Tomatenwürfel salzen und das Wasser abgießen, bevor Zwiebel und Zitrone dazukommen – so bleibt die Salsa knackig.',
    servings: 6,
    prepMinutes: 6,
    cookMinutes: 0,
    fridgeDays: 3,
    freezerDays: 0,
    eatCold: true,
    tags: ['basis-tomate', 'tex-mex', 'kalt'],
    equipment: [],
    steps: ['Tomaten würfeln, salzen, abtropfen lassen.', 'Zwiebel fein hacken.', 'Mit Zitronensaft, Chili und Kräutern mischen.'],
    per: [
      ['olivenoel', 3],
      ['tomaten', 50],
      ['zwiebel', 10],
      ['zitrone', 5],
      ['chiliflocken', 0.3],
      ['tk-kraeuter', 2],
    ],
  },
  {
    slug: 'smoky-bbq-sauce',
    name: 'Smoky-BBQ-Sauce',
    mealType: 'sauce',
    description: 'Basis Tomate: rauchige BBQ-Sauce aus Tomatenmark und geräuchertem Paprika, ohne Zuckerbombe.',
    flavorHack: 'Das Tomatenmark in der Pfanne anrösten, bis es rostrot wird – das bringt Tiefe, die man sonst nur aus Flaschensaucen kennt.',
    servings: 6,
    prepMinutes: 3,
    cookMinutes: 5,
    fridgeDays: 7,
    freezerDays: 60,
    eatCold: true,
    tags: ['basis-tomate', 'tex-mex'],
    equipment: ['Herd'],
    steps: ['Tomatenmark in der Pfanne anrösten.', 'Passata, Honig, Essig, Sojasauce und Paprikapulver dazu.', '5 Minuten einköcheln lassen.'],
    per: [
      ['tomatenmark', 10],
      ['honig', 5],
      ['essig', 5],
      ['sojasauce', 5],
      ['paprikapulver', 1],
      ['passata', 20],
    ],
  },
  {
    slug: 'chili-zitronen-skyr',
    name: 'Chili-Zitronen-Skyr',
    mealType: 'sauce',
    description: 'Basis Tomate (als kühlender Gegenpart): rauchig-scharfer Skyr statt Sauerrahm für Chili, Bowls und Wraps.',
    flavorHack: 'Geräuchertes Paprikapulver statt Chipotle – bringt den Rauch, der Tex-Mex so gut macht.',
    servings: 6,
    prepMinutes: 3,
    cookMinutes: 0,
    fridgeDays: 5,
    freezerDays: 0,
    eatCold: true,
    tags: ['basis-tomate', 'tex-mex', 'kalt'],
    equipment: [],
    steps: ['Skyr mit Paprikapulver, Chili, Zitronensaft und Knoblauch verrühren.', 'Mit Salz abschmecken.'],
    per: [
      ['skyr', 35],
      ['paprikapulver', 1],
      ['chiliflocken', 0.5],
      ['zitrone', 3],
      ['knoblauch', 1],
    ],
  },
  {
    slug: 'honig-senf-dressing',
    name: 'Honig-Senf-Dressing',
    mealType: 'sauce',
    description: 'Basis Senf-Zitrone: süß-scharfes Dressing für Bowls und Salate.',
    flavorHack: 'Zuerst Senf, Honig und Essig verrühren, dann das Öl langsam einrühren – so emulgiert es und trennt sich nicht in der Box.',
    servings: 6,
    prepMinutes: 3,
    cookMinutes: 0,
    fridgeDays: 7,
    freezerDays: 0,
    eatCold: true,
    tags: ['basis-senf', 'kalt'],
    equipment: [],
    steps: ['Senf, Honig und Essig verrühren.', 'Olivenöl langsam einrühren, dann Skyr.', 'Mit Salz und Pfeffer abschmecken.'],
    per: [
      ['senf', 8],
      ['honig', 5],
      ['olivenoel', 5],
      ['essig', 5],
      ['skyr', 15],
    ],
  },
  {
    slug: 'zitronen-kraeuter-marinade',
    name: 'Zitronen-Kräuter-Marinade',
    mealType: 'sauce',
    description: 'Basis Senf-Zitrone: frische Marinade für Hähnchen und Kartoffeln.',
    flavorHack: 'Zitronenabrieb statt nur Saft – der Abrieb bringt das Aroma, der Saft nur Säure.',
    servings: 6,
    prepMinutes: 4,
    cookMinutes: 0,
    fridgeDays: 5,
    freezerDays: 60,
    eatCold: true,
    tags: ['basis-senf', 'mediterran'],
    equipment: [],
    steps: ['Zitronenschale abreiben, Saft auspressen.', 'Mit Olivenöl, Knoblauch, Kräutern und Senf verrühren.', 'Fleisch darin mindestens 30 Minuten marinieren oder über Gemüse träufeln.'],
    per: [
      ['zitrone', 10],
      ['olivenoel', 4],
      ['knoblauch', 2],
      ['tk-kraeuter', 3],
      ['senf', 2],
    ],
  },
  {
    slug: 'kraeuter-knoblauch-dip',
    name: 'Kräuter-Knoblauch-Dip',
    mealType: 'sauce',
    description: 'Basis Senf-Zitrone: leichter Dip zu Auflauf, Schnitzel und Wedges.',
    flavorHack: 'Ein Hauch Senf im Dip macht ihn „runder“, ohne dass man ihn herausschmeckt.',
    servings: 6,
    prepMinutes: 3,
    cookMinutes: 0,
    fridgeDays: 5,
    freezerDays: 0,
    eatCold: true,
    tags: ['basis-senf', 'kalt'],
    equipment: [],
    steps: ['Skyr mit Kräutern, Knoblauch, Senf und Zitronensaft verrühren.', 'Salzen, pfeffern.'],
    per: [
      ['skyr', 30],
      ['tk-kraeuter', 3],
      ['knoblauch', 1],
      ['senf', 2],
      ['zitrone', 2],
    ],
  },

  // =================================================================== Mittag & Abend
  {
    slug: 'gyros-huehner-bowl',
    name: 'Gyros-Hühner-Bowl',
    mealType: 'main',
    description: 'Gyros-gewürzte Hühnerstreifen auf Reis mit Paprika, Gurke und Tomate – kalt genauso gut wie warm.',
    flavorHack: 'Das Huhn in Gyros-Gewürz, Öl und einem Löffel Skyr über Nacht marinieren und dann in der heißen Pfanne scharf anbraten – Röstaromen wie am Spieß. Zum Schluss Zitronensaft und Kräuter drüber – das macht es frisch statt schwer.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 20,
    fridgeDays: 4,
    freezerDays: 60,
    eatCold: true,
    tags: ['kalt', 'mediterran', 'high-protein'],
    equipment: ['Herd'],
    steps: [
      'Hühnerbrust in Streifen schneiden, mit Gyros-Gewürz und Öl marinieren.',
      'Reis kochen (1 Teil Reis, 1,5 Teile Wasser, 12 Minuten zugedeckt, 5 Minuten ziehen).',
      'Huhn in einer sehr heißen Pfanne in zwei Portionen je 5 Minuten scharf anbraten.',
      'Zwiebel in Ringe, Paprika, Gurke und Tomate würfeln.',
      'Reis, Huhn und Gemüse in Boxen verteilen, Sauce im extra Glas.',
    ],
    per: [
      ['huehnerbrust', 120],
      ['gyrosgewuerz', 4],
      ['rapsoel', 11],
      ['reis', 55],
      ['paprika', 80],
      ['gurke', 80],
      ['tomaten', 60],
      ['zwiebel', 20],
      ['zitrone', 6],
    ],
  },
  {
    slug: 'griechischer-nudelsalat',
    name: 'Griechischer Nudelsalat mit Hähnchen',
    mealType: 'main',
    description: 'Vollkornnudeln mit Hühnerbrust, Hirtenkäse, Gurke, Tomate und Oregano-Zitronen-Dressing.',
    flavorHack: 'Die Nudeln noch warm mit dem Dressing mischen – sie saugen es auf und der Salat schmeckt auch am dritten Tag nicht trocken.',
    servings: 2,
    prepMinutes: 15,
    cookMinutes: 12,
    fridgeDays: 3,
    freezerDays: 0,
    eatCold: true,
    tags: ['kalt', 'mediterran', 'high-protein'],
    equipment: ['Herd'],
    steps: [
      'Nudeln bissfest kochen, abgießen.',
      'Olivenöl, Zitronensaft, Oregano, Salz und Pfeffer verrühren, unter die warmen Nudeln mischen.',
      'Hühnerbrust würzen und 6 Minuten pro Seite braten, in Würfel schneiden.',
      'Gemüse würfeln, alles mischen, Hirtenkäse darüberbröseln.',
    ],
    per: [
      ['vollkornnudeln', 65],
      ['huehnerbrust', 110],
      ['hirtenkaese', 25],
      ['gurke', 70],
      ['tomaten', 70],
      ['paprika', 50],
      ['zwiebel', 15],
      ['olivenoel', 8],
      ['zitrone', 10],
      ['oregano', 1],
    ],
  },
  {
    slug: 'paprika-huehnerkeulen-wedges',
    name: 'Knusprige Paprika-Hühnerkeulen mit Ofen-Wedges & Brokkoli',
    mealType: 'main',
    description: 'Saftige Oberkeulen und Kartoffelspalten vom selben Blech, dazu Brokkoli.',
    flavorHack: 'Die Wedges vor dem Backen 5 Minuten in Salzwasser vorkochen und im Topf schütteln – die angeraute Oberfläche wird im Ofen richtig knusprig.',
    servings: 3,
    prepMinutes: 15,
    cookMinutes: 35,
    fridgeDays: 4,
    freezerDays: 60,
    eatCold: false,
    tags: ['ofen', 'herzhaft', 'österreichisch'],
    equipment: ['Backofen'],
    steps: [
      'Backofen auf 220 °C Umluft vorheizen.',
      'Kartoffeln in Spalten schneiden, 5 Minuten vorkochen, abgießen und schütteln.',
      'Keulen mit Paprikapulver, Salz, Knoblauch und Öl einreiben.',
      'Keulen und Wedges auf ein Blech, 30–35 Minuten backen, einmal wenden.',
      'Brokkoli die letzten 10 Minuten mit aufs Blech. Zum Schluss Zitronensaft über Huhn und Brokkoli.',
    ],
    per: [
      ['huehnerkeule', 150],
      ['paprikapulver', 3],
      ['kartoffeln', 230],
      ['rapsoel', 4],
      ['tk-brokkoli', 150],
      ['knoblauch', 2],
      ['zitrone', 10],
    ],
  },
  {
    slug: 'puten-kofta-couscous',
    name: 'Puten-Köfte mit Zitronen-Couscous & Zucchini',
    mealType: 'main',
    description: 'Türkische Köfte aus Putenfaschiertem mit Kreuzkümmel und Kräutern, fluffiger Zitronen-Couscous und gebratene Zucchini.',
    flavorHack: 'Geriebene Zwiebel samt Saft in die Masse – die Köfte bleiben auch nach drei Tagen in der Box saftig.',
    servings: 2,
    prepMinutes: 15,
    cookMinutes: 15,
    fridgeDays: 3,
    freezerDays: 60,
    eatCold: true,
    tags: ['mediterran', 'high-protein'],
    equipment: ['Herd'],
    steps: [
      'Putenfaschiertes mit geriebener Zwiebel, Knoblauch, Kreuzkümmel, Salz und Pfeffer verkneten.',
      'Zu länglichen Köfte formen, in wenig Öl rundum 8–10 Minuten braten.',
      'Couscous mit heißer Brühe übergießen, 5 Minuten quellen, mit Zitrone und Kräutern auflockern.',
      'Zucchini in Halbmonde schneiden und in derselben Pfanne 4 Minuten braten.',
    ],
    per: [
      ['putenfaschiertes', 135],
      ['zwiebel', 20],
      ['kreuzkuemmel', 1],
      ['knoblauch', 3],
      ['couscous', 55],
      ['gemuesebruehe', 2],
      ['zitrone', 10],
      ['zucchini', 150],
      ['olivenoel', 7],
      ['tk-kraeuter', 3],
    ],
  },
  {
    slug: 'chicken-teriyaki-bowl',
    name: 'Chicken Teriyaki Bowl',
    mealType: 'main',
    description: 'Glasierte Hühnerbrust auf Reis mit Wokgemüse, Frühlingszwiebel und Sesam.',
    flavorHack: 'Die Glaze erst ganz am Ende in die Pfanne und 1 Minute mit dem Huhn einkochen – sie überzieht jedes Stück wie Lack.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 20,
    fridgeDays: 4,
    freezerDays: 60,
    eatCold: true,
    tags: ['asia', 'kalt', 'high-protein', 'einfrieren'],
    equipment: ['Herd'],
    steps: [
      'Reis kochen.',
      'Hühnerbrust würfeln und in heißem Öl 6 Minuten anbraten.',
      'Wokgemüse dazugeben und 4 Minuten mitbraten.',
      'Teriyaki-Glaze darübergießen und 1 Minute einkochen lassen.',
      'Auf Reis verteilen, mit Frühlingszwiebel und Sesam bestreuen.',
    ],
    per: [
      ['huehnerbrust', 125],
      ['reis', 50],
      ['tk-wokgemuese', 150],
      ['rapsoel', 11],
      ['fruehlingszwiebel', 10],
      ['sesam', 3],
      ['chiliflocken', 0.3],
    ],
  },
  {
    slug: 'kalte-erdnuss-nudeln',
    name: 'Kalte Erdnuss-Nudeln mit Hähnchen & Edamame',
    mealType: 'main',
    description: 'Vollkornspaghetti in Satay-Sauce mit Hühnerbrust, Edamame, Karotte und Gurke – gemacht, um kalt gegessen zu werden.',
    flavorHack: 'Die gekochten Nudeln kalt abspülen und sofort mit einem Teil der Sauce mischen – sie kleben nicht und nehmen den Geschmack an.',
    servings: 3,
    prepMinutes: 15,
    cookMinutes: 12,
    fridgeDays: 4,
    freezerDays: 0,
    eatCold: true,
    tags: ['asia', 'kalt', 'high-protein'],
    equipment: ['Herd'],
    steps: [
      'Spaghetti kochen, Edamame die letzten 3 Minuten mitkochen, kalt abspülen.',
      'Hühnerbrust in Salzwasser 12 Minuten gar ziehen lassen, zerzupfen.',
      'Karotte und Gurke in feine Streifen schneiden.',
      'Alles mit der Erdnuss-Sauce mischen, Frühlingszwiebel darüber.',
    ],
    per: [
      ['vollkornnudeln', 60],
      ['huehnerbrust', 100],
      ['tk-edamame', 60],
      ['karotten', 50],
      ['gurke', 70],
      ['fruehlingszwiebel', 10],
      ['chiliflocken', 0.3],
    ],
  },
  {
    slug: 'korean-beef-bowl',
    name: 'Korean Beef Bowl mit Brokkoli',
    mealType: 'main',
    description: 'Knusprig gebratenes Rinderfaschiertes mit Knoblauch und Ingwer, Reis, Brokkoli und Edamame.',
    flavorHack: 'Das Faschierte flach in die heiße Pfanne drücken und 3 Minuten nicht anrühren – erst dann zerteilen. So entstehen knusprige Stücke statt grauer Krümel.',
    servings: 3,
    prepMinutes: 10,
    cookMinutes: 20,
    fridgeDays: 4,
    freezerDays: 60,
    eatCold: false,
    tags: ['asia', 'herzhaft'],
    equipment: ['Herd'],
    steps: [
      'Reis kochen.',
      'Faschiertes in die heiße Pfanne drücken, 3 Minuten anbraten lassen, dann zerteilen.',
      'Knoblauch und Ingwer dazu, 1 Minute mitbraten, mit dem Dressing ablöschen.',
      'Brokkoli und Edamame 5 Minuten dämpfen.',
      'Alles auf Reis verteilen, Frühlingszwiebel darüber.',
    ],
    per: [
      ['sesam', 5],
      ['rinderfaschiertes', 130],
      ['reis', 50],
      ['tk-brokkoli', 150],
      ['tk-edamame', 30],
      ['knoblauch', 3],
      ['ingwer', 3],
      ['fruehlingszwiebel', 10],
      ['chiliflocken', 0.5],
    ],
  },
  {
    slug: 'linsen-kokos-curry',
    name: 'Rotes Linsen-Kokos-Curry mit Hähnchen',
    mealType: 'main',
    description: 'Cremiges Curry mit roten Linsen, Spinat und Hühnerbrust auf Reis – wird nach dem Einfrieren sogar besser.',
    flavorHack: 'Currypulver, Ingwer und Zwiebel 2 Minuten in Öl rösten, bevor irgendetwas Flüssiges dazukommt – das ist der Unterschied zwischen „Curry-Sauce“ und Curry.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    fridgeDays: 4,
    freezerDays: 90,
    eatCold: false,
    tags: ['asia', 'einfrieren', 'one-pot', 'budget'],
    equipment: ['Herd'],
    steps: [
      'Zwiebel, Ingwer und Currypulver in Öl 2 Minuten rösten.',
      'Hühnerbrust würfeln, kurz mitbraten.',
      'Linsen, stückige Tomaten, Kokosmilch und 200 ml Wasser dazu, 15 Minuten köcheln.',
      'Spinat einrühren, 3 Minuten ziehen lassen, mit Salz und einem Spritzer Zitrone abschmecken.',
      'Mit Reis in Boxen füllen. Do/Fr-Portionen sofort einfrieren.',
    ],
    per: [
      ['huehnerbrust', 100],
      ['rote-linsen', 45],
      ['kokosmilch-light', 120],
      ['tk-spinat', 80],
      ['tomaten-stueckig', 100],
      ['zwiebel', 30],
      ['currypulver', 3],
      ['ingwer', 3],
      ['rapsoel', 3],
      ['reis', 35],
      ['zitrone', 8],
      ['knoblauch', 3],
    ],
  },
  {
    slug: 'burrito-bowl',
    name: 'Burrito-Bowl mit Rinderfaschiertem',
    mealType: 'main',
    description: 'Mexikanisch gewürztes Faschiertes, Reis, Bohnen, Mais und Paprika mit Skyr-Topping.',
    flavorHack: 'Kreuzkümmel und geräuchertes Paprikapulver direkt ins heiße Fett, dann einen Schuss Wasser – das Faschierte wird saftig und würzig wie im Burrito-Laden. Ein Spritzer Zitrone über den Reis ersetzt Limettenreis.',
    servings: 3,
    prepMinutes: 10,
    cookMinutes: 20,
    fridgeDays: 4,
    freezerDays: 60,
    eatCold: true,
    tags: ['tex-mex', 'kalt'],
    equipment: ['Herd'],
    steps: [
      'Reis kochen.',
      'Faschiertes krümelig anbraten, Gewürze dazu, mit einem Schuss Wasser ablöschen.',
      'Bohnen und Mais abspülen.',
      'Alles in Boxen schichten, Paprika und Salat obenauf, Skyr als Topping.',
    ],
    per: [
      ['rinderfaschiertes', 110],
      ['reis', 45],
      ['kidneybohnen', 80],
      ['mais', 40],
      ['paprika', 60],
      ['eisberg', 30],
      ['skyr', 30],
      ['kreuzkuemmel', 1],
      ['paprikapulver', 2],
      ['zitrone', 8],
      ['tk-kraeuter', 2],
    ],
  },
  {
    slug: 'huehner-fajita-wraps',
    name: 'Hühner-Fajita-Wraps',
    mealType: 'main',
    description: 'Paprika-Zwiebel-Huhn mit Rauchpaprika, in Wraps gerollt – die Füllung wird vorbereitet, gerollt wird frisch.',
    flavorHack: 'Paprika und Zwiebel in einer brennheißen Pfanne anbraten, bis sie schwarze Stellen haben – dieses leichte Anbrennen ist der Fajita-Geschmack.',
    servings: 3,
    prepMinutes: 10,
    cookMinutes: 15,
    fridgeDays: 4,
    freezerDays: 60,
    eatCold: true,
    tags: ['tex-mex', 'kalt', 'einfrieren'],
    equipment: ['Herd'],
    steps: [
      'Hühnerbrust in Streifen schneiden, mit Paprikapulver, Kreuzkümmel und Salz würzen.',
      'Paprika und Zwiebel in Streifen schneiden.',
      'Huhn in der heißen Pfanne 5 Minuten braten, herausnehmen, dann das Gemüse scharf anbraten.',
      'Füllung auskühlen lassen und portionieren. Wraps erst am Vorabend oder in der Früh rollen.',
    ],
    per: [
      ['wraps', 93],
      ['huehnerbrust', 115],
      ['paprika', 100],
      ['zwiebel', 40],
      ['rapsoel', 8],
      ['paprikapulver', 2],
      ['kreuzkuemmel', 1],
      ['zitrone', 5],
      ['knoblauch', 2],
    ],
  },
  {
    slug: 'linsen-bolognese',
    name: 'One-Pot-Linsen-Bolognese',
    mealType: 'main',
    description: 'Bolognese mit Rinderfaschiertem, roten Linsen und verstecktem Spinat – die Nudeln kochen im selben Topf, nur ein Topf zum Abwaschen.',
    flavorHack: 'Ein Löffel Sojasauce in die Bolognese – niemand schmeckt Soja heraus, aber das Fleisch schmeckt „fleischiger“.',
    servings: 3,
    prepMinutes: 10,
    cookMinutes: 25,
    fridgeDays: 4,
    freezerDays: 90,
    eatCold: false,
    tags: ['one-pot', 'einfrieren', 'österreichisch'],
    equipment: ['Herd'],
    steps: [
      'Zwiebel, Karotte und Knoblauch fein würfeln und in einem großen Topf anschwitzen.',
      'Faschiertes dazu und krümelig anbraten, Tomatenmark 1 Minute mitrösten, Sojasauce dazu.',
      'Passata, Linsen, Oregano und 400 ml Wasser dazu, aufkochen.',
      'Nudeln und Spinat direkt dazugeben und 12 Minuten köcheln, öfter umrühren.',
      'Mozzarella darüberzupfen und schmelzen lassen.',
    ],
    per: [
      ['olivenoel', 4],
      ['vollkornnudeln', 50],
      ['rinderfaschiertes', 90],
      ['rote-linsen', 25],
      ['passata', 150],
      ['karotten', 40],
      ['zwiebel', 30],
      ['knoblauch', 3],
      ['oregano', 1],
      ['mozzarella-light', 30],
      ['sojasauce', 3],
      ['tk-spinat', 50],
      ['tomatenmark', 10],
    ],
  },
  {
    slug: 'puten-chili-con-carne',
    name: 'Puten-Chili con Carne mit Reis',
    mealType: 'main',
    description: 'Chili mit Putenfaschiertem, Bohnen, Mais und einem Hauch Kakao – der Klassiker zum Einfrieren.',
    flavorHack: 'Ein Teelöffel Kakao und ein Spritzer Zitrone am Schluss – das Chili schmeckt runder und nicht nach Tomatensauce.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 30,
    fridgeDays: 4,
    freezerDays: 90,
    eatCold: false,
    tags: ['tex-mex', 'einfrieren', 'one-pot', 'budget'],
    equipment: ['Herd'],
    steps: [
      'Zwiebel und Paprika würfeln, in Öl anschwitzen.',
      'Faschiertes dazu und anbraten, Gewürze und Kakao kurz mitrösten.',
      'Tomaten, Bohnen und Mais dazu, 20 Minuten köcheln lassen.',
      'Reis kochen. Chili mit Reis in Boxen – die Do/Fr-Portionen sofort einfrieren.',
    ],
    per: [
      ['putenfaschiertes', 120],
      ['kidneybohnen', 80],
      ['tomaten-stueckig', 150],
      ['mais', 30],
      ['paprika', 60],
      ['zwiebel', 30],
      ['kakao', 2],
      ['kreuzkuemmel', 1],
      ['paprikapulver', 2],
      ['rapsoel', 6],
      ['reis', 40],
      ['zitrone', 5],
      ['knoblauch', 3],
    ],
  },
  {
    slug: 'zitronen-huhn-kartoffelsalat',
    name: 'Zitronen-Hähnchen mit steirischem Kartoffelsalat',
    mealType: 'main',
    description: 'Zartes Zitronen-Huhn und saftiger Essig-Öl-Kartoffelsalat mit Kürbiskernen – kalt am besten.',
    flavorHack: 'Die Kartoffeln noch heiß mit warmer Brühe, Essig und Senf marinieren – nur so wird der Kartoffelsalat „speckig“ wie bei der Oma.',
    servings: 2,
    prepMinutes: 15,
    cookMinutes: 25,
    fridgeDays: 3,
    freezerDays: 0,
    eatCold: true,
    tags: ['kalt', 'österreichisch', 'high-protein'],
    equipment: ['Herd'],
    steps: [
      'Kartoffeln in der Schale 20 Minuten kochen, schälen, blättrig schneiden.',
      'Brühe mit Essig, Senf, Zwiebel und Öl aufkochen und über die heißen Kartoffeln gießen.',
      'Hühnerbrust mit der Zitronen-Marinade 6 Minuten pro Seite braten, aufschneiden.',
      'Gurke, Frühlingszwiebel und Schnittlauch unter den Salat, geröstete Kürbiskerne darüber.',
    ],
    per: [
      ['huehnerbrust', 125],
      ['kartoffeln', 260],
      ['gurke', 60],
      ['zwiebel', 20],
      ['essig', 10],
      ['senf', 5],
      ['rapsoel', 8],
      ['gemuesebruehe', 2],
      ['kuerbiskerne', 12],
      ['fruehlingszwiebel', 10],
      ['tk-kraeuter', 3],
    ],
  },
  {
    slug: 'suesskartoffel-huehner-bowl',
    name: 'Süßkartoffel-Hühner-Bowl mit Kichererbsen',
    mealType: 'main',
    description: 'Geröstete Süßkartoffel mit Kreuzkümmel, knusprige Kichererbsen, Ofenkarotten, Paprika-Huhn und Salat mit Honig-Senf – süß, salzig, crunchy.',
    flavorHack: 'Kichererbsen trocken tupfen und mit auf das Süßkartoffel-Blech – nach 25 Minuten sind sie knusprig wie Chips.',
    servings: 3,
    prepMinutes: 15,
    cookMinutes: 30,
    fridgeDays: 4,
    freezerDays: 0,
    eatCold: true,
    tags: ['ofen', 'kalt', 'high-protein'],
    equipment: ['Backofen'],
    steps: [
      'Backofen auf 210 °C Umluft vorheizen.',
      'Süßkartoffel würfeln, mit Kichererbsen, Karottenstücken, Öl, Paprikapulver, Kreuzkümmel und Salz aufs Blech, 25–30 Minuten rösten.',
      'Hühnerbrust würzen und die letzten 18 Minuten mit aufs Blech legen.',
      'Salat schneiden, alles in Boxen, Hirtenkäse darüber, Dressing extra.',
    ],
    per: [
      ['huehnerbrust', 110],
      ['suesskartoffel', 170],
      ['kichererbsen', 50],
      ['eisberg', 40],
      ['paprikapulver', 2],
      ['rapsoel', 10],
      ['hirtenkaese', 15],
      ['zitrone', 8],
      ['karotten', 90],
      ['kreuzkuemmel', 1],
    ],
  },
  {
    slug: 'huehner-brokkoli-auflauf',
    name: 'Hühner-Brokkoli-Nudelauflauf',
    mealType: 'main',
    description: 'Cremiger Nudelauflauf mit leichter Béchamel, Hühnerbrust und Brokkoli, mit Mozzarella überbacken.',
    flavorHack: 'Eine Prise Muskat und ein Teelöffel Senf in die Béchamel – schmeckt nach Käsesauce, obwohl kaum Käse drin ist.',
    servings: 3,
    prepMinutes: 15,
    cookMinutes: 30,
    fridgeDays: 4,
    freezerDays: 90,
    eatCold: false,
    tags: ['ofen', 'einfrieren', 'high-protein'],
    equipment: ['Herd', 'Backofen'],
    steps: [
      'Nudeln 2 Minuten kürzer als angegeben kochen, Brokkoli die letzten 3 Minuten mit.',
      'Mehl in einem Topf anschwitzen, Milch nach und nach einrühren, 3 Minuten köcheln, würzen.',
      'Hühnerbrust würfeln und kurz anbraten.',
      'Alles in eine Form, Mozzarella darüber, bei 200 °C 15 Minuten überbacken.',
    ],
    per: [
      ['olivenoel', 4],
      ['vollkornnudeln', 55],
      ['huehnerbrust', 85],
      ['tk-brokkoli', 150],
      ['milch', 120],
      ['mehl', 8],
      ['mozzarella-light', 45],
      ['knoblauch', 2],
      ['senf', 2],
      ['tk-kraeuter', 2],
    ],
  },
  {
    slug: 'paprikahendl-light',
    name: 'Paprikahendl light mit Reis',
    mealType: 'main',
    description: 'Der österreichische Klassiker: Hühnerbrust in samtiger Paprika-Rahm-Sauce – mit Skyr statt Sauerrahm.',
    flavorHack: 'Das Paprikapulver nur kurz vom Herd genommen ins Fett rühren – verbrannter Paprika wird bitter. Den Skyr erst ganz am Ende und nicht mehr kochen.',
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 25,
    fridgeDays: 4,
    freezerDays: 60,
    eatCold: false,
    tags: ['österreichisch', 'high-protein'],
    equipment: ['Herd'],
    steps: [
      'Zwiebel fein würfeln und in Öl goldbraun rösten.',
      'Topf kurz vom Herd, Paprikapulver und Tomatenmark einrühren, mit 200 ml Wasser ablöschen.',
      'Hühnerbrust würfeln und in der Sauce 12 Minuten sanft köcheln. Paprika dazu.',
      'Reis kochen. Vom Herd nehmen, Skyr einrühren, abschmecken.',
    ],
    per: [
      ['huehnerbrust', 120],
      ['paprika', 100],
      ['zwiebel', 50],
      ['tomatenmark', 10],
      ['paprikapulver', 5],
      ['skyr', 50],
      ['rapsoel', 12],
      ['reis', 55],
      ['knoblauch', 3],
    ],
  },
  {
    slug: 'smash-burger-wedges',
    name: 'Smash-Burger mit Ofen-Wedges',
    mealType: 'main',
    description: 'Dünn gedrückter Rinder-Burger mit knuspriger Kruste, Käse und Senf, dazu Wedges – das Wochenend-Essen.',
    flavorHack: 'Die Faschierten-Kugel in der brennheißen Pfanne mit einem Topfboden flach drücken und erst nach 2 Minuten wenden – die Kruste ist der ganze Geschmack. Gurkenscheiben 10 Minuten in Essig und einer Prise Salz ziehen lassen – schnelle Pickles.',
    servings: 1,
    prepMinutes: 10,
    cookMinutes: 30,
    fridgeDays: 1,
    freezerDays: 0,
    eatCold: false,
    tags: ['wochenende', 'herzhaft'],
    equipment: ['Herd', 'Backofen'],
    steps: [
      'Wedges wie bei den Ofen-Keulen vorkochen und bei 220 °C 25 Minuten backen.',
      'Faschiertes zu einer Kugel formen, in der heißen Pfanne flach drücken, salzen.',
      'Nach 2 Minuten wenden, Käse darauf, 1 Minute.',
      'Brötchen anrösten, mit Senf, Salat, Tomate, Zwiebel und dem Patty belegen.',
    ],
    per: [
      ['rinderfaschiertes', 110],
      ['burgerbroetchen', 75],
      ['kaese-light', 10],
      ['tomaten', 40],
      ['eisberg', 20],
      ['zwiebel', 15],
      ['kartoffeln', 150],
      ['rapsoel', 3],
      ['senf', 5],
      ['gurke', 30],
    ],
  },
  {
    slug: 'shakshuka-kichererbsen',
    name: 'Shakshuka mit Kichererbsen & Hüttenkäse',
    mealType: 'main',
    description: 'Eier in würziger Paprika-Tomatensauce mit Kichererbsen, dazu Brot zum Tunken.',
    flavorHack: 'Kreuzkümmel und Paprikapulver zuerst 30 Sekunden in der Pfanne rösten – erst dann Zwiebel und Paprika dazu.',
    servings: 1,
    prepMinutes: 5,
    cookMinutes: 20,
    fridgeDays: 1,
    freezerDays: 0,
    eatCold: false,
    tags: ['wochenende', 'vegetarisch', 'one-pot', 'budget'],
    equipment: ['Herd'],
    steps: [
      'Gewürze in der Pfanne anrösten, Zwiebel und Paprika 5 Minuten braten.',
      'Tomaten und Kichererbsen dazu, 8 Minuten einkochen lassen.',
      'Mulden drücken, Eier hineinschlagen, zugedeckt 6 Minuten stocken lassen.',
      'Hüttenkäse und Kräuter darüber, mit Brot servieren.',
    ],
    per: [
      ['eier', 100],
      ['tomaten-stueckig', 200],
      ['kichererbsen', 80],
      ['paprika', 80],
      ['zwiebel', 40],
      ['huettenkaese', 80],
      ['kreuzkuemmel', 1],
      ['paprikapulver', 2],
      ['vollkornbrot', 50],
      ['knoblauch', 3],
      ['chiliflocken', 0.3],
    ],
  },
  {
    slug: 'cornflakes-schnitzel',
    name: 'Knuspriges Cornflakes-Schnitzel mit Erdäpfel-Gurkensalat',
    mealType: 'main',
    description: 'Wiener Art aus dem Ofen: goldenes Hühnerschnitzel mit Cornflakes-Panier, dazu lauwarmer Erdäpfelsalat mit Gurke und Schnittlauch – Sonntag wie bei der Oma, nur leichter.',
    flavorHack: 'Die Cornflakes nur grob zerdrücken und die Schnitzel mit einem Hauch Öl besprühen – so wird die Panier im Ofen goldener als in der Pfanne.',
    servings: 2,
    prepMinutes: 15,
    cookMinutes: 25,
    fridgeDays: 2,
    freezerDays: 0,
    eatCold: false,
    tags: ['wochenende', 'österreichisch', 'ofen', 'high-protein'],
    equipment: ['Herd', 'Backofen'],
    steps: [
      'Kartoffeln kochen, schälen, blättrig schneiden und mit warmer Brühe, Essig, Senf, Zwiebel und Öl marinieren.',
      'Hühnerbrust dünn klopfen, salzen, in Mehl, Ei und Cornflakes wenden.',
      'Bei 220 °C 15–18 Minuten backen, einmal wenden.',
      'Gurke hobeln, salzen, ausdrücken und mit Kräutern unter den Erdäpfelsalat heben. Mit Zitronenspalten servieren.',
    ],
    per: [
      ['huehnerbrust', 125],
      ['cornflakes', 25],
      ['eier', 20],
      ['mehl', 8],
      ['kartoffeln', 220],
      ['essig', 10],
      ['senf', 5],
      ['rapsoel', 8],
      ['zwiebel', 20],
      ['gemuesebruehe', 2],
      ['zitrone', 15],
      ['gurke', 80],
      ['tk-kraeuter', 2],
    ],
  },
  {
    slug: 'tortilla-pizza',
    name: 'Knusper-Tortilla-Pizza mit Schinken & Pilzen',
    mealType: 'main',
    description: 'Zwei Wraps als hauchdünner Pizzaboden, belegt mit Schinken, Pilzen, Paprika und Mozzarella – in 10 Minuten.',
    flavorHack: 'Den Wrap zuerst 2 Minuten allein im heißen Ofen vorbacken – dann wird er knusprig wie Pizza aus dem Holzofen.',
    servings: 1,
    prepMinutes: 5,
    cookMinutes: 10,
    fridgeDays: 1,
    freezerDays: 0,
    eatCold: false,
    tags: ['wochenende', 'schnell', 'ofen'],
    equipment: ['Backofen'],
    steps: [
      'Ofen auf 230 °C vorheizen, Wraps 2 Minuten vorbacken.',
      'Passata mit geriebenem Knoblauch, Oregano und einer Prise Salz verrühren und aufstreichen.',
      'Schinken, Pilze, Paprika und Mozzarella verteilen.',
      '7–8 Minuten backen.',
    ],
    per: [
      ['wraps', 124],
      ['passata', 60],
      ['mozzarella-light', 60],
      ['putenschinken', 70],
      ['champignons', 60],
      ['paprika', 40],
      ['oregano', 1],
      ['knoblauch', 2],
      ['chiliflocken', 0.2],
    ],
  },
];

export const RECIPES: RecipeSeed[] = [...BASE_RECIPES, ...SOUTHERN_RECIPES, ...WEEKEND_RECIPES, ...SIMPLE_RECIPES];
