import type { RecipeSeed } from './recipes';

/**
 * Weekend food: breakfasts with a bit more time, "Fakeaways" (what you'd otherwise order –
 * Döner, Big Mac, Nuggets – rebuilt with lean protein) and one Gönn-Essen per week (tag
 * "goennung"), where the ingredients may cost 5–10 € a portion.
 */
export const WEEKEND_RECIPES: RecipeSeed[] = [
  // =================================================================== Wochenend-Frühstück
  {
    slug: 'kaiserschmarrn-light',
    name: 'Kaiserschmarrn light mit Apfelmus',
    mealType: 'breakfast',
    description: 'Fluffiger, in der Pfanne zerrissener Schmarrn mit Topfen im Teig – außen karamellig, innen saftig, dazu Apfelmus.',
    flavorHack: 'Eiweiß extra steif schlagen und unterheben, dann einen Teelöffel Honig in die Pfanne und die Stücke darin karamellisieren – schmeckt wie auf der Hütte.',
    servings: 1,
    prepMinutes: 8,
    cookMinutes: 10,
    fridgeDays: 1,
    freezerDays: 0,
    eatCold: false,
    tags: ['wochenende', 'süß', 'österreichisch', 'high-protein', 'vegetarisch'],
    equipment: ['Herd'],
    steps: [
      'Eier trennen. Dotter mit Magertopfen, Milch, Mehl und einer Prise Salz glatt rühren.',
      'Eiklar mit einer Prise Salz steif schlagen und locker unterheben.',
      'In einer beschichteten Pfanne mit wenig Öl bei mittlerer Hitze 4 Minuten backen, bis die Unterseite goldbraun ist.',
      'Vierteln, wenden, mit zwei Gabeln in Stücke reißen, Honig darüber und 2 Minuten karamellisieren.',
      'Mit Zimt bestäuben, Apfelmus dazu.',
    ],
    per: [
      ['eier', 120],
      ['magertopfen', 150],
      ['mehl', 30],
      ['milch', 50],
      ['rapsoel', 4],
      ['honig', 6],
      ['zimt', 0.5],
      ['apfelmus', 100],
    ],
  },
  {
    slug: 'protein-french-toast',
    name: 'Protein-French-Toast mit Beeren & Vanille-Skyr',
    mealType: 'breakfast',
    description: 'In Zimt-Eiermilch getränktes Vollkornbrot, goldbraun gebraten, mit warmen Beeren und cremigem Skyr.',
    flavorHack: 'Das Brot 30 Sekunden pro Seite in der Eiermilch lassen, nicht länger – dann wird es innen puddingweich und außen knusprig. Eine Prise Salz in die Eiermilch.',
    servings: 1,
    prepMinutes: 4,
    cookMinutes: 8,
    fridgeDays: 0,
    freezerDays: 0,
    eatCold: false,
    tags: ['wochenende', 'süß', 'high-protein', 'vegetarisch'],
    equipment: ['Herd'],
    steps: [
      'Eier mit Milch, Zimt und einer Prise Salz verquirlen.',
      'Brotscheiben kurz darin wenden und in wenig Öl je 2–3 Minuten pro Seite goldbraun braten.',
      'Beeren in der Pfanne kurz erwärmen.',
      'Mit Skyr, Beeren und einem Faden Honig servieren.',
    ],
    per: [
      ['vollkornbrot', 100],
      ['eier', 90],
      ['milch', 60],
      ['zimt', 0.5],
      ['rapsoel', 4],
      ['skyr', 150],
      ['tk-beeren', 80],
      ['honig', 5],
    ],
  },
  {
    slug: 'fruehstuecks-burrito',
    name: 'Frühstücks-Burrito mit Ei, Bohnen & Salsa',
    mealType: 'breakfast',
    description: 'Rührei mit Bohnen, Frühlingszwiebel und Käse im knusprig angebratenen Wrap, dazu frische Tomatensalsa.',
    flavorHack: 'Den gerollten Burrito mit der Naht nach unten in die trockene Pfanne legen und kurz andrücken – er bleibt zu und bekommt Röstaromen.',
    servings: 1,
    prepMinutes: 5,
    cookMinutes: 6,
    fridgeDays: 1,
    freezerDays: 30,
    eatCold: false,
    tags: ['wochenende', 'herzhaft', 'tex-mex', 'high-protein', 'vegetarisch'],
    equipment: ['Herd'],
    steps: [
      'Tomaten und Frühlingszwiebel fein würfeln, salzen – das ist die Salsa.',
      'Eier mit Skyr verquirlen, mit Bohnen und Paprikapulver bei kleiner Hitze cremig stocken lassen.',
      'Auf den Wrap geben, Käse darüber, Salsa dazu, fest einrollen.',
      'In der trockenen Pfanne auf beiden Seiten 1 Minute anrösten.',
    ],
    per: [
      ['wraps', 62],
      ['eier', 90],
      ['skyr', 60],
      ['kidneybohnen', 50],
      ['kaese-light', 15],
      ['tomaten', 60],
      ['fruehlingszwiebel', 10],
      ['paprikapulver', 0.5],
      ['rapsoel', 2],
    ],
  },

  // =================================================================== Fakeaways
  {
    slug: 'huehner-duerum',
    name: 'Hühner-Dürüm mit Knoblauch-Skyr & Kraut',
    mealType: 'main',
    description: 'Der Döner-Stand zu Hause: würziges Gyros-Huhn, Knoblauchsauce, Kraut, Tomate und Zwiebel im gerösteten Wrap – mit fast doppelt so viel Protein.',
    flavorHack: 'Das Huhn in dünne Streifen schneiden und in der glühend heißen Pfanne ohne Rühren anbraten, bis die Ränder dunkel werden – genau diese Kanten machen den Dönergeschmack.',
    servings: 1,
    prepMinutes: 10,
    cookMinutes: 8,
    fridgeDays: 1,
    freezerDays: 0,
    eatCold: false,
    tags: ['wochenende', 'fakeaway', 'herzhaft', 'high-protein'],
    equipment: ['Herd'],
    steps: [
      'Hühnerbrust in feine Streifen schneiden, mit Gyros-Gewürz, Chili und Öl marinieren.',
      'Skyr mit geriebenem Knoblauch, Zitronensaft und Salz verrühren.',
      'Huhn in einer sehr heißen Pfanne 5 Minuten scharf anbraten.',
      'Wrap in der Pfanne kurz erwärmen, mit Sauce bestreichen, Kraut, Salat, Tomate, Zwiebel und Huhn drauf, fest einrollen.',
    ],
    per: [
      ['wraps', 62],
      ['huehnerbrust', 150],
      ['gyrosgewuerz', 3],
      ['rapsoel', 6],
      ['chiliflocken', 0.3],
      ['skyr', 60],
      ['knoblauch', 3],
      ['zitrone', 5],
      ['krautsalat', 60],
      ['eisberg', 30],
      ['tomaten', 50],
      ['zwiebel', 20],
    ],
  },
  {
    slug: 'big-mac-bowl',
    name: 'Big-Mac-Bowl mit Spezialsauce',
    mealType: 'main',
    description: 'Alles vom Burger in der Schüssel: knuspriges Rinderfaschiertes, Salat, Gurkerl, Zwiebel, Käse, Ofenkartoffeln und die berühmte Sauce – nur leichter.',
    flavorHack: 'Spezialsauce: Skyr, Senf, fein gehackte Essiggurke bzw. Gurke mit Essig, Paprikapulver und ein Klecks Mayo – 10 Minuten ziehen lassen, dann schmeckt sie wie das Original.',
    servings: 1,
    prepMinutes: 10,
    cookMinutes: 25,
    fridgeDays: 2,
    freezerDays: 0,
    eatCold: false,
    tags: ['wochenende', 'fakeaway', 'herzhaft'],
    equipment: ['Herd', 'Backofen'],
    steps: [
      'Kartoffeln würfeln, mit wenig Öl und Salz bei 220 °C 25 Minuten knusprig backen.',
      'Sauce anrühren: Skyr, Mayo, Senf, gehackte Gurke, Essig, Paprikapulver, Honig.',
      'Faschiertes flach in die heiße Pfanne drücken, 3 Minuten nicht anrühren, dann zerteilen und salzen.',
      'Salat, Tomate, Gurke und Zwiebel in die Schüssel, Faschiertes und Kartoffeln darauf, Käse darüber, Sauce drüber.',
    ],
    per: [
      ['rinderfaschiertes', 130],
      ['kartoffeln', 150],
      ['rapsoel', 2],
      ['eisberg', 80],
      ['gurke', 50],
      ['zwiebel', 20],
      ['tomaten', 50],
      ['kaese-light', 10],
      ['skyr', 50],
      ['mayonnaise', 2],
      ['senf', 5],
      ['essig', 3],
      ['paprikapulver', 0.5],
      ['honig', 3],
    ],
  },
  {
    slug: 'crispy-chicken-nuggets',
    name: 'Crispy Chicken Nuggets aus dem Ofen mit Wedges',
    mealType: 'main',
    description: 'Knusprige Cornflakes-Nuggets und Kartoffel-Wedges vom Blech, zum Dippen in BBQ-Sauce – besser als vom Drive-in.',
    flavorHack: 'Geräuchertes Paprikapulver und Knoblauch in die Cornflakes-Panier und die Nuggets auf ein Gitter legen – so werden sie rundum knusprig.',
    servings: 2,
    prepMinutes: 15,
    cookMinutes: 25,
    fridgeDays: 2,
    freezerDays: 60,
    eatCold: false,
    tags: ['wochenende', 'fakeaway', 'ofen', 'high-protein'],
    equipment: ['Backofen'],
    steps: [
      'Backofen auf 220 °C vorheizen. Kartoffeln in Spalten schneiden, mit der Hälfte des Öls und Salz aufs Blech, 10 Minuten vorbacken.',
      'Hühnerbrust in Nugget-Stücke schneiden, salzen.',
      'Cornflakes grob zerdrücken, mit Paprikapulver und Knoblauch mischen.',
      'Nuggets in Mehl, verquirltem Ei und Cornflakes wenden, mit restlichem Öl beträufeln.',
      'Zu den Wedges aufs Blech, 15 Minuten backen, einmal wenden.',
    ],
    per: [
      ['huehnerbrust', 160],
      ['cornflakes', 25],
      ['eier', 20],
      ['mehl', 8],
      ['paprikapulver', 2],
      ['knoblauch', 2],
      ['kartoffeln', 200],
      ['rapsoel', 6],
    ],
  },
  {
    slug: 'rahm-geschnetzeltes',
    name: 'Rahm-Geschnetzeltes vom Huhn mit Champignons & Reis',
    mealType: 'main',
    description: 'Zartes Hühnergeschnetzeltes in cremiger Champignon-Sauce mit einem Spritzer Zitrone – Wiener Beisl-Gefühl ohne Obers.',
    flavorHack: 'Die Champignons ohne Öl in der heißen Pfanne anrösten, bis sie Farbe haben und das Wasser verdampft ist – erst dann Zwiebel und Fett. So schmecken sie nussig statt gekocht.',
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 20,
    fridgeDays: 3,
    freezerDays: 60,
    eatCold: false,
    tags: ['wochenende', 'österreichisch', 'high-protein'],
    equipment: ['Herd'],
    steps: [
      'Reis kochen.',
      'Champignons blättrig schneiden und trocken anrösten, dann Zwiebel und Öl dazu.',
      'Hühnerbrust in Streifen schneiden, mitbraten, bis sie rundum weiß ist.',
      'Maisstärke in der kalten Milch verrühren, dazugießen und 3 Minuten köcheln lassen.',
      'Vom Herd nehmen, Skyr, Senf, Kräuter und Zitrone einrühren, mit Salz, Pfeffer und Paprikapulver abschmecken.',
    ],
    per: [
      ['huehnerbrust', 150],
      ['champignons', 120],
      ['zwiebel', 40],
      ['rapsoel', 6],
      ['milch', 120],
      ['maisstaerke', 6],
      ['skyr', 40],
      ['senf', 5],
      ['tk-kraeuter', 3],
      ['zitrone', 5],
      ['paprikapulver', 1],
      ['reis', 60],
    ],
  },
  {
    slug: 'faschierte-laibchen',
    name: 'Faschierte Laibchen mit Erdäpfelpüree & Gurkensalat',
    mealType: 'main',
    description: 'Omas Fleischlaberl aus Rind und Pute, cremiges Püree und ein knackiger Gurkensalat mit Dille-Skyr – Sonntagsessen.',
    flavorHack: 'Eine eingeweichte Scheibe Brot oder Semmelbrösel mit Milch in die Masse und einen Löffel Senf – die Laibchen bleiben saftig wie beim Wirt.',
    servings: 2,
    prepMinutes: 20,
    cookMinutes: 20,
    fridgeDays: 3,
    freezerDays: 90,
    eatCold: false,
    tags: ['wochenende', 'österreichisch', 'herzhaft'],
    equipment: ['Herd'],
    steps: [
      'Kartoffeln schälen, würfeln und 15 Minuten weich kochen.',
      'Faschiertes mit Ei, Semmelbröseln, fein gehackter Zwiebel, Knoblauch, Senf, Salz und Pfeffer verkneten, 4 Laibchen formen.',
      'In wenig Öl bei mittlerer Hitze je 5 Minuten pro Seite braten.',
      'Kartoffeln abgießen, mit heißer Milch und Butter zu Püree stampfen, salzen, Muskat.',
      'Gurke hobeln, salzen, ausdrücken, mit Skyr, Essig und Kräutern anmachen.',
    ],
    per: [
      ['rinderfaschiertes', 60],
      ['putenfaschiertes', 90],
      ['eier', 15],
      ['semmelbroesel', 15],
      ['zwiebel', 30],
      ['knoblauch', 2],
      ['senf', 5],
      ['rapsoel', 4],
      ['kartoffeln', 220],
      ['milch', 60],
      ['butter', 3],
      ['gurke', 100],
      ['skyr', 30],
      ['essig', 5],
      ['tk-kraeuter', 2],
    ],
  },
  {
    slug: 'honig-knoblauch-haehnchen',
    name: 'Honig-Knoblauch-Hähnchen mit Reis & Brokkoli',
    mealType: 'main',
    description: 'Klebrig-glänzendes Hähnchen in Honig-Knoblauch-Soja-Glasur mit Sesam – das Lieblingsgericht vom Asia-Imbiss, selbst gemacht.',
    flavorHack: 'Den Knoblauch erst in den letzten 30 Sekunden in die Pfanne, dann sofort mit Sojasauce und Honig ablöschen – so bleibt er süßlich und wird nicht bitter.',
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 15,
    fridgeDays: 3,
    freezerDays: 60,
    eatCold: true,
    tags: ['wochenende', 'fakeaway', 'asia', 'high-protein'],
    equipment: ['Herd'],
    steps: [
      'Reis kochen, Brokkoli die letzten 5 Minuten dämpfen.',
      'Hühnerbrust würfeln, in Maisstärke wenden und in heißem Öl 6 Minuten goldbraun braten.',
      'Knoblauch dazu, 30 Sekunden, dann Sojasauce, Honig und 3 EL Wasser – 1 Minute einkochen, bis es glänzt.',
      'Mit Reis und Brokkoli anrichten, Sesam, Frühlingszwiebel, Chili und Zitrone darüber.',
    ],
    per: [
      ['huehnerbrust', 150],
      ['maisstaerke', 5],
      ['rapsoel', 6],
      ['knoblauch', 6],
      ['sojasauce', 12],
      ['honig', 12],
      ['reis', 60],
      ['tk-brokkoli', 150],
      ['sesam', 3],
      ['fruehlingszwiebel', 10],
      ['chiliflocken', 0.3],
      ['zitrone', 5],
    ],
  },

  // =================================================================== Gönn-Essen
  {
    slug: 'garnelen-burrata-pasta',
    name: 'Garnelen-Tomaten-Pasta mit Burrata',
    mealType: 'main',
    description: 'Knoblauch-Chili-Garnelen in würziger Tomatensauce, Vollkornspaghetti und eine halbe Burrata, die beim Anschneiden zerläuft. Das Gönn-Essen der Woche.',
    flavorHack: 'Die Garnelen nur 1 Minute pro Seite anbraten und herausnehmen, erst am Ende zurück in die Sauce – so bleiben sie saftig. Ein Schuss Nudelwasser macht die Sauce seidig.',
    servings: 1,
    prepMinutes: 10,
    cookMinutes: 15,
    fridgeDays: 1,
    freezerDays: 0,
    eatCold: false,
    tags: ['goennung', 'wochenende', 'mediterran', 'high-protein'],
    equipment: ['Herd'],
    steps: [
      'Spaghetti in Salzwasser bissfest kochen, eine Tasse Nudelwasser aufheben.',
      'Garnelen trocken tupfen, in Olivenöl 1 Minute pro Seite braten, herausnehmen.',
      'Knoblauch und Chili im selben Öl 30 Sekunden anschwitzen, Tomatenmark 1 Minute rösten, Tomaten dazu, 8 Minuten köcheln.',
      'Spaghetti, Garnelen und einen Schuss Nudelwasser untermischen, mit Zitrone und Salz abschmecken.',
      'Burrata obenauf, Parmesan und Kräuter drüber.',
    ],
    per: [
      ['vollkornnudeln', 80],
      ['garnelen', 180],
      ['olivenoel', 8],
      ['knoblauch', 5],
      ['chiliflocken', 0.5],
      ['tomatenmark', 10],
      ['tomaten-stueckig', 150],
      ['zitrone', 5],
      ['burrata', 60],
      ['parmesan', 8],
      ['tk-kraeuter', 3],
    ],
  },
  {
    slug: 'lachs-poke-bowl',
    name: 'Lachs-Poke-Bowl mit Avocado & Edamame',
    mealType: 'main',
    description: 'Gebratener Sesam-Lachs auf gewürztem Sushireis mit Avocado, Edamame, Gurke, Karotte und scharfer Skyr-Mayo. Das Gönn-Essen der Woche – und voller Omega-3.',
    flavorHack: 'Den Reis noch warm mit Essig, Honig und einer Prise Salz würzen – wie beim Sushi-Laden. Den Lachs auf der Hautseite braten und erst ganz am Ende kurz wenden.',
    servings: 1,
    prepMinutes: 15,
    cookMinutes: 15,
    fridgeDays: 1,
    freezerDays: 0,
    eatCold: true,
    tags: ['goennung', 'wochenende', 'asia'],
    equipment: ['Herd'],
    steps: [
      'Sushireis waschen und mit der 1,2-fachen Menge Wasser 12 Minuten zugedeckt garen, 10 Minuten ziehen lassen.',
      'Essig, Honig und eine Prise Salz unter den warmen Reis mischen.',
      'Lachs salzen, auf der Hautseite 4 Minuten braten, wenden, 1 Minute, mit Sojasauce ablöschen, Sesam drüber.',
      'Edamame 3 Minuten kochen, Gurke, Karotte und Avocado schneiden.',
      'Skyr mit Sriracha und Mayo verrühren. Alles auf dem Reis anrichten, Frühlingszwiebel drüber.',
    ],
    per: [
      ['lachs', 140],
      ['sushireis', 70],
      ['essig', 5],
      ['honig', 3],
      ['sojasauce', 10],
      ['sesam', 3],
      ['tk-edamame', 60],
      ['gurke', 60],
      ['karotten', 40],
      ['avocado', 40],
      ['fruehlingszwiebel', 10],
      ['skyr', 30],
      ['sriracha', 5],
      ['mayonnaise', 3],
    ],
  },
  {
    slug: 'steak-rosmarin-kartoffeln',
    name: 'Rinderhüftsteak mit Rosmarin-Kartoffeln & Champignons',
    mealType: 'main',
    description: 'Ein richtiges Steak: außen kräftig angebraten, innen rosa, mit knusprigen Rosmarin-Kartoffeln, Knoblauch-Champignons und Kräuterbutter. Das Gönn-Essen der Woche.',
    flavorHack: 'Steak 30 Minuten vorher aus dem Kühlschrank nehmen, trocken tupfen, in der rauchend heißen Pfanne je 2–3 Minuten braten, dann Butter, Knoblauch und Kräuter dazu und das Steak damit übergießen. 5 Minuten rasten lassen.',
    servings: 1,
    prepMinutes: 10,
    cookMinutes: 30,
    fridgeDays: 1,
    freezerDays: 0,
    eatCold: false,
    tags: ['goennung', 'wochenende', 'high-protein'],
    equipment: ['Herd', 'Backofen'],
    steps: [
      'Kartoffeln vierteln, mit Öl, Salz und Kräutern (Rosmarin) bei 220 °C 30 Minuten knusprig backen.',
      'Steak 30 Minuten vorher aus dem Kühlschrank nehmen, trocken tupfen, salzen.',
      'Champignons trocken anrösten, Zwiebel und etwas Butter dazu, mit Knoblauch fertig braten.',
      'Steak in der sehr heißen Pfanne je 2–3 Minuten pro Seite braten, restliche Butter, Knoblauch und Kräuter dazu, übergießen.',
      '5 Minuten rasten lassen, gegen die Faser aufschneiden, pfeffern. Salat mit Balsamico dazu.',
    ],
    per: [
      ['rinderhueftsteak', 200],
      ['kartoffeln', 250],
      ['rapsoel', 6],
      ['tk-kraeuter', 4],
      ['champignons', 120],
      ['zwiebel', 20],
      ['butter', 8],
      ['knoblauch', 4],
      ['eisberg', 50],
      ['tomaten', 60],
      ['balsamico', 5],
    ],
  },
  {
    slug: 'wiener-schnitzel-kalb',
    name: 'Wiener Schnitzel vom Kalb mit Erdäpfelsalat & Preiselbeeren',
    mealType: 'main',
    description: 'Das Original: dünn geklopftes Kalbsschnitzel mit souffliert-welliger Panier, steirischer Erdäpfelsalat, Preiselbeeren und Zitrone. Das Gönn-Essen der Woche.',
    flavorHack: 'Die Panier nur locker andrücken und die Pfanne beim Herausbacken sanft schwenken, sodass Fett über das Schnitzel schwappt – dann wirft die Panier die typischen Wellen.',
    servings: 1,
    prepMinutes: 20,
    cookMinutes: 25,
    fridgeDays: 1,
    freezerDays: 0,
    eatCold: false,
    tags: ['goennung', 'wochenende', 'österreichisch', 'high-protein'],
    equipment: ['Herd'],
    steps: [
      'Kartoffeln in der Schale kochen, schälen, blättrig schneiden, mit warmer Brühe, Essig, Senf und Zwiebel marinieren.',
      'Kalbsschnitzel zwischen Frischhaltefolie dünn klopfen, salzen.',
      'In Mehl, verquirltem Ei und Semmelbröseln wenden, Panier nur locker andrücken.',
      'In reichlich heißem Öl schwimmend 2 Minuten pro Seite goldgelb herausbacken, auf Küchenpapier abtropfen lassen (gerechnet ist das Öl, das das Schnitzel aufnimmt).',
      'Mit Zitronenspalten, Preiselbeeren, Gurke im Salat und Erdäpfelsalat servieren.',
    ],
    per: [
      ['kalbsschnitzel', 160],
      ['mehl', 10],
      ['eier', 25],
      ['semmelbroesel', 30],
      ['rapsoel', 14],
      ['kartoffeln', 220],
      ['essig', 10],
      ['senf', 5],
      ['zwiebel', 20],
      ['gemuesebruehe', 2],
      ['gurke', 60],
      ['preiselbeeren', 25],
      ['zitrone', 15],
    ],
  },
  {
    slug: 'double-smash-burger-deluxe',
    name: 'Double Smash Burger mit Cheddar & Bacon, dazu Süßkartoffel-Pommes',
    mealType: 'main',
    description: 'Zwei dünne, knusprig gedrückte Patties mit geschmolzenem Cheddar, Bacon, Burger-Sauce und Gurkerl im Brioche, dazu Süßkartoffel-Pommes aus dem Ofen. Gönn-Essen für Burger-Tage.',
    flavorHack: 'Die Patties in der brennheißen Pfanne mit einem Topf flach drücken, salzen, nach 90 Sekunden wenden, Cheddar drauf, Deckel kurz drauf – der Käse schmilzt über die Ränder.',
    servings: 1,
    prepMinutes: 15,
    cookMinutes: 30,
    fridgeDays: 1,
    freezerDays: 0,
    eatCold: false,
    tags: ['goennung', 'wochenende', 'fakeaway', 'high-protein'],
    equipment: ['Herd', 'Backofen'],
    steps: [
      'Süßkartoffel in Stifte schneiden, mit Öl, Paprikapulver und Salz bei 220 °C 25–30 Minuten backen.',
      'Burger-Sauce: Skyr, Senf, Sriracha und gehackte Gurke verrühren.',
      'Speck knusprig braten, herausnehmen.',
      'Faschiertes in zwei Kugeln teilen, in der heißen Pfanne flach drücken, salzen, nach 90 Sekunden wenden, Cheddar drauf.',
      'Brioche anrösten, Sauce, Salat, Tomate, Zwiebel, Patties, Speck und Gurkerl stapeln.',
    ],
    per: [
      ['rinderfaschiertes', 150],
      ['brioche', 75],
      ['cheddar', 20],
      ['speck', 12],
      ['eisberg', 20],
      ['tomaten', 40],
      ['gurke', 30],
      ['zwiebel', 20],
      ['skyr', 30],
      ['senf', 5],
      ['sriracha', 3],
      ['suesskartoffel', 180],
      ['rapsoel', 4],
      ['paprikapulver', 1],
    ],
  },
];
