import type { RecipeSeed } from './recipes';

/**
 * "Einfach"-Modus: basic plates for days you don't feel like a recipe – one pan or one tray,
 * few ingredients, same macros as the elaborate dishes. The day's sauce from the prep still
 * goes on top, so simple doesn't mean bland. Tag "einfach" marks them for the day switch.
 */
export const SIMPLE_RECIPES: RecipeSeed[] = [
  {
    slug: 'einfach-huhn-reis-brokkoli',
    name: 'Hähnchen, Reis & Brokkoli',
    mealType: 'main',
    description: 'Der Klassiker: saftige Hühnerbrust mit Paprika und Knoblauch, Basmatireis, Brokkoli und ein Spritzer Zitrone.',
    flavorHack: 'Das Huhn vor dem Braten flach klopfen und kräftig salzen – es gart gleichmäßig und bleibt saftig. Zitrone erst ganz am Schluss.',
    servings: 3,
    prepMinutes: 5,
    cookMinutes: 20,
    fridgeDays: 4,
    freezerDays: 60,
    eatCold: true,
    tags: ['einfach', 'kalt', 'high-protein', 'budget'],
    equipment: ['Herd'],
    steps: [
      'Reis kochen, Brokkoli die letzten 5 Minuten mitdämpfen.',
      'Hühnerbrust flach klopfen, mit Salz, Paprikapulver und Knoblauch würzen.',
      'In Öl 5–6 Minuten pro Seite braten, 3 Minuten rasten lassen, aufschneiden.',
      'Mit Zitronensaft beträufeln, in Boxen verteilen.',
    ],
    per: [
      ['huehnerbrust', 130],
      ['reis', 65],
      ['tk-brokkoli', 200],
      ['rapsoel', 10],
      ['paprikapulver', 1],
      ['knoblauch', 2],
      ['zitrone', 5],
    ],
  },
  {
    slug: 'einfach-blech-huhn-kartoffeln',
    name: 'Hähnchen vom Blech mit Kartoffeln & Karotten',
    mealType: 'main',
    description: 'Alles auf ein Blech, 35 Minuten Ofen, fertig: Paprika-Huhn, Kartoffeln und Karotten mit Kräutern.',
    flavorHack: 'Kartoffeln und Karotten zuerst 15 Minuten allein backen und das Huhn erst dazulegen – so ist alles gleichzeitig fertig und nichts trocken.',
    servings: 3,
    prepMinutes: 10,
    cookMinutes: 35,
    fridgeDays: 4,
    freezerDays: 0,
    eatCold: true,
    tags: ['einfach', 'ofen', 'kalt', 'high-protein', 'budget'],
    equipment: ['Backofen'],
    steps: [
      'Backofen auf 210 °C. Kartoffeln und Karotten in Stücke schneiden, mit Öl, Salz und Kräutern aufs Blech, 15 Minuten backen.',
      'Hühnerbrust mit Paprikapulver, Knoblauch und Salz würzen, dazulegen.',
      'Weitere 20 Minuten backen.',
    ],
    per: [
      ['huehnerbrust', 135],
      ['kartoffeln', 250],
      ['karotten', 150],
      ['rapsoel', 11],
      ['paprikapulver', 2],
      ['knoblauch', 2],
      ['tk-kraeuter', 2],
    ],
  },
  {
    slug: 'einfach-nudeln-fleischsauce',
    name: 'Nudeln mit Puten-Fleischsauce',
    mealType: 'main',
    description: 'Schnelle Fleischsauce aus Putenfaschiertem, Passata und Oregano über Vollkornnudeln, mit etwas Parmesan.',
    flavorHack: 'Das Faschierte richtig braun anbraten, bevor die Passata dazukommt – die Röststoffe sind der Geschmack.',
    servings: 3,
    prepMinutes: 5,
    cookMinutes: 20,
    fridgeDays: 4,
    freezerDays: 90,
    eatCold: false,
    tags: ['einfach', 'einfrieren', 'high-protein', 'budget'],
    equipment: ['Herd'],
    steps: [
      'Nudeln kochen.',
      'Zwiebel und Knoblauch anschwitzen, Faschiertes dazu und braun anbraten.',
      'Passata und Oregano dazu, 10 Minuten köcheln, salzen.',
      'Mit Parmesan servieren.',
    ],
    per: [
      ['vollkornnudeln', 70],
      ['putenfaschiertes', 130],
      ['passata', 150],
      ['zwiebel', 20],
      ['knoblauch', 2],
      ['oregano', 1],
      ['parmesan', 5],
      ['olivenoel', 6],
    ],
  },
  {
    slug: 'einfach-thunfisch-reis-bowl',
    name: 'Thunfisch-Reis-Bowl mit Mais & Gurke',
    mealType: 'main',
    description: 'Reis, Thunfisch, Mais und Gurke mit Senf-Skyr-Dressing – kalt, in 15 Minuten fertig, ohne Herd-Stress.',
    flavorHack: 'Den Reis noch warm mit einem Löffel Essig und einer Prise Salz mischen – schmeckt kalt dann nicht nach Resten.',
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 15,
    fridgeDays: 2,
    freezerDays: 0,
    eatCold: true,
    tags: ['einfach', 'kalt', 'high-protein', 'budget'],
    equipment: ['Herd'],
    steps: [
      'Reis kochen und auskühlen lassen.',
      'Thunfisch abtropfen, Gurke würfeln, Mais abspülen.',
      'Skyr mit Senf, Zitrone, Olivenöl, Salz und Pfeffer verrühren.',
      'Alles in Boxen, Dressing darüber.',
    ],
    per: [
      ['reis', 65],
      ['thunfisch', 105],
      ['mais', 60],
      ['gurke', 100],
      ['skyr', 40],
      ['senf', 3],
      ['zitrone', 5],
      ['olivenoel', 10],
    ],
  },
  {
    slug: 'einfach-pute-paprika-reispfanne',
    name: 'Pute-Paprika-Reispfanne',
    mealType: 'main',
    description: 'Eine Pfanne: Putenfaschiertes, Paprika, Zwiebel und Reis in Paprika-Tomaten-Würze, mit einem Klecks Skyr.',
    flavorHack: 'Tomatenmark und Paprikapulver 30 Sekunden im Fett rösten, bevor der Reis dazukommt – macht aus „Reispfanne“ ein richtiges Essen.',
    servings: 3,
    prepMinutes: 10,
    cookMinutes: 20,
    fridgeDays: 4,
    freezerDays: 60,
    eatCold: true,
    tags: ['einfach', 'one-pot', 'kalt', 'einfrieren', 'budget'],
    equipment: ['Herd'],
    steps: [
      'Reis kochen.',
      'Faschiertes krümelig anbraten, Zwiebel und Paprika dazu, 5 Minuten braten.',
      'Tomatenmark und Paprikapulver kurz mitrösten, Reis unterheben, salzen.',
      'Mit Skyr servieren.',
    ],
    per: [
      ['putenfaschiertes', 140],
      ['reis', 55],
      ['paprika', 120],
      ['zwiebel', 30],
      ['tomatenmark', 10],
      ['paprikapulver', 2],
      ['rapsoel', 7],
      ['skyr', 40],
    ],
  },
  {
    slug: 'einfach-ofenkartoffel-huettenkaese',
    name: 'Ofenkartoffel mit Kräuter-Hüttenkäse & Schinken',
    mealType: 'main',
    description: 'Große Ofenkartoffel, aufgebrochen und gefüllt mit Kräuter-Hüttenkäse und Putenschinken, dazu Gurkensalat.',
    flavorHack: 'Die Kartoffel vor dem Backen mit Salz einreiben und direkt aufs Gitter legen – die Schale wird knusprig wie am Christkindlmarkt.',
    servings: 1,
    prepMinutes: 5,
    cookMinutes: 45,
    fridgeDays: 1,
    freezerDays: 0,
    eatCold: false,
    tags: ['einfach', 'ofen', 'high-protein', 'budget'],
    equipment: ['Backofen'],
    steps: [
      'Kartoffel waschen, mit Salz einreiben, bei 200 °C 45 Minuten backen (oder halbiert 30 Minuten).',
      'Hüttenkäse mit Kräutern, Salz und Pfeffer verrühren.',
      'Kartoffel aufbrechen, Hüttenkäse und Schinken hinein.',
      'Gurke in Scheiben, salzen, mit Olivenöl beträufeln – fertig.',
    ],
    per: [
      ['kartoffeln', 320],
      ['huettenkaese', 200],
      ['putenschinken', 50],
      ['tk-kraeuter', 3],
      ['gurke', 100],
      ['olivenoel', 6],
    ],
  },
];
